'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {supabase} from '@/lib/supabase';
import styles from './family.module.css';

type R=Record<string,any>;

export default function MemberManager({onReady}:{onReady:(data:{uid:string;email:string;name:string;hid:string;members:R[];profiles:R[];house:R|null})=>void}){
 const router=useRouter();
 const [uid,setUid]=useState(''),[email,setEmail]=useState(''),[name,setName]=useState('');
 const [house,setHouse]=useState<R|null>(null),[members,setMembers]=useState<R[]>([]),[profiles,setProfiles]=useState<R[]>([]);
 const [invite,setInvite]=useState(''),[joinCode,setJoinCode]=useState(''),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(true);
 const profileMap=useMemo(()=>Object.fromEntries(profiles.map(p=>[p.id,p])),[profiles]);
 const myRole=members.find(m=>m.user_id===uid)?.role;

 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getUser();if(!data.user){router.replace('/login');return}const u=data.user;setUid(u.id);setEmail(u.email||'');let display='';const p=await supabase.from('profiles').select('*').eq('id',u.id).maybeSingle();if(p.data){display=p.data.display_name||'';setName(display);if(p.data.email!==u.email)await supabase.from('profiles').update({email:u.email||''}).eq('id',u.id)}else await supabase.from('profiles').insert({id:u.id,email:u.email||'',display_name:null});const h=await supabase.from('households').select('id,name,created_by,period_start_day').order('created_at').limit(1);if(h.data?.[0]){setHouse(h.data[0]);await loadMembers(h.data[0],u.id,u.email||'',display)}else{onReady({uid:u.id,email:u.email||'',name:display,hid:'',members:[],profiles:[],house:null});setBusy(false)}})()},[router]);

 async function loadMembers(h:R,currentUid=uid,currentEmail=email,currentName=name){const fresh=await supabase.from('households').select('id,name,created_by,period_start_day').eq('id',h.id).maybeSingle();const currentHouse=fresh.data||h;setHouse(currentHouse);const m=await supabase.from('household_members').select('user_id,role,created_at').eq('household_id',h.id).order('created_at');if(m.error){setErr(m.error.message);setBusy(false);return}const ms=m.data||[];setMembers(ms);const ids=ms.map(x=>x.user_id);let ps:R[]=[];if(ids.length){const p=await supabase.from('profiles').select('id,email,display_name').in('id',ids);ps=p.data||[];setProfiles(ps)}onReady({uid:currentUid,email:currentEmail,name:currentName,hid:h.id,members:ms,profiles:ps,house:currentHouse});setBusy(false)}
 async function saveProfile(e:FormEvent){e.preventDefault();setErr('');const r=await supabase.from('profiles').upsert({id:uid,email,display_name:name.trim()||null});if(r.error)setErr(r.error.message);else{setMsg('Nama profil tersimpan.');if(house)await loadMembers(house,uid,email,name)}}
 async function makeInvite(){setErr('');const r=await supabase.rpc('create_household_invite',{p_household_id:house?.id});if(r.error)setErr(r.error.message);else{setInvite(r.data);setMsg('Kode undangan aktif 24 jam.')}}
 async function join(e:FormEvent){e.preventDefault();setErr('');const r=await supabase.rpc('join_household_by_code',{p_code:joinCode.trim()});if(r.error)setErr(r.error.message);else{router.push('/dashboard');router.refresh()}}
 async function removeMember(userId:string){const p=profileMap[userId];const label=p?.display_name||p?.email||'anggota ini';if(!confirm(`Keluarkan ${label} dari household? Mereka akan kehilangan akses ke seluruh data household ini.`))return;setErr('');setMsg('');const r=await supabase.from('household_members').delete().eq('household_id',house?.id).eq('user_id',userId);if(r.error)setErr(r.error.message);else if(house){setMsg(`${label} sudah dikeluarkan dari household.`);await loadMembers(house)}}
 if(busy)return <div className={styles.card}>Memuat anggota…</div>;
 return <>{err&&<div className={styles.error}>{err}</div>}{msg&&<div className={styles.success}>{msg}</div>}<div className={styles.grid}><section className={styles.card}><h2>Profil Saya</h2><form onSubmit={saveProfile}><label>Nama yang tampil<input value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Zainal"/></label><label>Email<input value={email} disabled/></label><button className={styles.primary}>Simpan Profil</button></form></section>{!house?<section className={styles.card}><h2>Gabung Household</h2><p className={styles.muted}>Masukkan kode undangan dari owner.</p><form onSubmit={join}><label>Kode undangan<input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())}/></label><button className={styles.primary}>Gabung</button></form></section>:<section className={styles.card}><h2>Undang Anggota</h2><p className={styles.muted}>Anggota login memakai akun masing-masing, tetapi datanya tetap satu household.</p>{myRole==='owner'?<><button className={styles.primary} onClick={makeInvite}>Buat Kode Undangan</button>{invite&&<div className={styles.code}><span>Kode undangan</span><strong>{invite}</strong><small>Berlaku 24 jam dan sekali pakai.</small></div>}</>:<p className={styles.muted}>Hanya owner yang dapat membuat kode undangan.</p>}</section>}</div>{house&&<section className={styles.card}><h2>Anggota Household</h2>{myRole==='owner'&&<p className={styles.muted}>Sebagai kepala keluarga / owner, kamu dapat mengeluarkan member kapan saja. Owner tidak dapat mengeluarkan dirinya sendiri.</p>}<div className={styles.members}>{members.map(m=>{const p=profileMap[m.user_id];return <div className={styles.member} key={m.user_id}><div className={styles.avatar}>{(p?.display_name||p?.email||'?').slice(0,1).toUpperCase()}</div><div><b>{p?.display_name||p?.email||'Anggota keluarga'}</b><span>{p?.email||m.user_id}</span></div><span className={styles.role}>{m.role==='owner'?'Owner':'Member'}</span>{myRole==='owner'&&m.user_id!==uid&&<button className={styles.remove} onClick={()=>removeMember(m.user_id)}>Keluarkan</button>}</div>})}</div></section>}</>;
}
