'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {supabase} from '@/lib/supabase';
import {Toast} from '@/app/components/UiKit';

type R=Record<string,any>;
const rp=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const sum=(rows:R[],field='amount')=>rows.reduce((s,x)=>s+Number(x[field]||0),0);
export default function AdminPageV2(){
 const router=useRouter();const[loading,setLoading]=useState(true),[err,setErr]=useState(''),[toast,setToast]=useState(''),[profiles,setProfiles]=useState<R[]>([]),[houses,setHouses]=useState<R[]>([]),[members,setMembers]=useState<R[]>([]),[settings,setSettings]=useState<R|null>(null),[events,setEvents]=useState<R[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState(''),[finance,setFinance]=useState<Record<string,R[]>>({}),[financeLoading,setFinanceLoading]=useState(false);
 const profileMap=useMemo(()=>Object.fromEntries(profiles.map(p=>[p.id,p])),[profiles]);
 async function reload(){setErr('');const{data:u}=await supabase.auth.getUser();if(!u.user){router.replace('/login');return}const admin=await supabase.from('platform_admins').select('role').eq('user_id',u.user.id).maybeSingle();if(admin.error||!admin.data){setErr('Akun ini bukan admin Family Vault.');setLoading(false);return}const[p,h,m,s,e]=await Promise.all([supabase.from('profiles').select('*').order('created_at',{ascending:false}),supabase.from('households').select('*').order('created_at',{ascending:false}),supabase.from('household_members').select('*').order('created_at',{ascending:false}),supabase.from('platform_settings').select('*').eq('id',true).maybeSingle(),supabase.from('security_events').select('*').order('created_at',{ascending:false}).limit(40)]);if(p.error||h.error||m.error){setErr(p.error?.message||h.error?.message||m.error?.message||'Gagal memuat admin');setLoading(false);return}setProfiles(p.data||[]);setHouses(h.data||[]);setMembers(m.data||[]);setSettings(s.data||null);setEvents(e.data||[]);setLoading(false)}
 useEffect(()=>{reload()},[]);
 async function patchProfile(id:string,patch:R,msg:string){const{data:u}=await supabase.auth.getUser();const r=await supabase.from('profiles').update({...patch,...(patch.status==='approved'?{approved_at:new Date().toISOString(),approved_by:u.user?.id||null}:{})}).eq('id',id);if(r.error)setErr(r.error.message);else{setToast(msg);reload()}}
 async function patchHouse(id:string,status:string){const{data:u}=await supabase.auth.getUser();const patch:any={status};if(status==='active'){patch.approved_at=new Date().toISOString();patch.approved_by=u.user?.id||null}const r=await supabase.from('households').update(patch).eq('id',id);if(r.error)setErr(r.error.message);else{setToast(`Household ${status}.`);reload()}}
 async function removeMember(hid:string,uid:string){if(!confirm('Cabut akses anggota ini?'))return;const r=await supabase.from('household_members').delete().eq('household_id',hid).eq('user_id',uid);if(r.error)setErr(r.error.message);else{setToast('Akses anggota dicabut.');reload()}}
 async function deleteHouse(h:R){if(!confirm(`Hapus permanen household “${h.name}” beserta datanya?`))return;const typed=prompt(`Ketik nama household persis: ${h.name}`);if(typed!==h.name)return;const r=await supabase.from('households').delete().eq('id',h.id);if(r.error)setErr(r.error.message);else{setToast('Household dihapus permanen.');reload()}}
 async function saveSettings(e:FormEvent){e.preventDefault();if(!settings)return;const{data:u}=await supabase.auth.getUser();const r=await supabase.from('platform_settings').update({maintenance_enabled:!!settings.maintenance_enabled,maintenance_title:settings.maintenance_title,maintenance_message:settings.maintenance_message,announcement_enabled:!!settings.announcement_enabled,announcement_title:settings.announcement_title,announcement_message:settings.announcement_message,updated_by:u.user?.id||null,updated_at:new Date().toISOString()}).eq('id',true);if(r.error)setErr(r.error.message);else{setToast('Pengaturan platform disimpan.');reload()}}
 async function viewFinance(hid:string){setSelected(hid);setFinanceLoading(true);setErr('');const tables=['income','expenses','budgets','obligations','etf_assets','gold_assets','dividend_stocks','savings','debts','wishlists'];const data:Record<string,R[]>={};for(const t of tables){const r=await supabase.from(t).select('*').eq('household_id',hid).is('archived_at',null);if(r.error){setErr(r.error.message);setFinanceLoading(false);return}data[t]=r.data||[]}const ids=(k:string)=>data[k]?.map(x=>x.id)||[];for(const[t,col,arr]of[['saving_transactions','saving_id',ids('savings')],['debt_payments','debt_id',ids('debts')]] as any[]){if(!arr.length){data[t]=[];continue}const r=await supabase.from(t).select('*').in(col,arr);data[t]=r.data||[]}setFinance(data);setFinanceLoading(false)}
 const filteredProfiles=profiles.filter(p=>(status==='all'||p.status===status)&&`${p.display_name||''} ${p.email||''}`.toLowerCase().includes(q.toLowerCase()));
 const filteredHouses=houses.filter(h=>`${h.name} ${profileMap[h.created_by]?.email||''}`.toLowerCase().includes(q.toLowerCase()));
 const pendingUsers=profiles.filter(p=>p.status==='pending').length,activeHouses=houses.filter(h=>h.status==='active').length,pendingHouses=houses.filter(h=>h.status==='pending').length,suspended=profiles.filter(p=>p.status==='suspended').length;
 const selectedHouse=houses.find(h=>h.id===selected),totalIncome=sum(finance.income||[]),totalExpenses=sum(finance.expenses||[]),savingValue=sum(finance.saving_transactions||[]),debtRemaining=(finance.debts||[]).reduce((s,d)=>s+Math.max(0,Number(d.original_amount||0)-sum((finance.debt_payments||[]).filter(x=>x.debt_id===d.id))),0);
 if(loading)return <main className="admin-shell"><div className="admin-card">Memuat Admin Family Vault…</div></main>;
 if(err&&profiles.length===0)return <main className="admin-shell"><div className="admin-card"><h1>Admin Family Vault</h1><p className="admin-error">{err}</p><Link href="/dashboard">← Kembali</Link></div></main>;
 return <main className="admin-shell"><header className="admin-head"><div><div className="kicker">Platform Control</div><h1>Admin Family Vault</h1><p>Kontrol akses, maintenance, household, dan observability platform.</p></div><div className="admin-actions"><Link className="btn alt" href="/security">Security</Link><Link className="btn alt" href="/dashboard">Dashboard Saya</Link></div></header>{err&&<p className="status error">{err}</p>}
  <section className="admin-metrics refined-admin-metrics"><div><span>Total akun</span><b>{profiles.length}</b></div><div><span>Pending akun</span><b>{pendingUsers}</b></div><div><span>Household aktif</span><b>{activeHouses}</b></div><div><span>Pending household</span><b>{pendingHouses}</b></div><div><span>Suspended</span><b>{suspended}</b></div></section>
  <section className="admin-section"><div className="admin-title"><div><div className="kicker">Maintenance & Announcement</div><h2>Platform Control</h2></div><span>{settings?.maintenance_enabled?'MAINTENANCE ON':'Normal'}</span></div>{settings&&<form className="admin-card maintenance-form" onSubmit={saveSettings}><div className="maintenance-toggles"><label><input type="checkbox" checked={!!settings.maintenance_enabled} onChange={e=>setSettings({...settings,maintenance_enabled:e.target.checked})}/><span><b>Maintenance Mode</b><small>Memblokir user biasa, admin tetap dapat masuk.</small></span></label><label><input type="checkbox" checked={!!settings.announcement_enabled} onChange={e=>setSettings({...settings,announcement_enabled:e.target.checked})}/><span><b>Announcement Banner</b><small>Tampil di dashboard seluruh user.</small></span></label></div><div className="admin-form-grid"><label>Judul maintenance<input value={settings.maintenance_title||''} onChange={e=>setSettings({...settings,maintenance_title:e.target.value})}/></label><label>Judul announcement<input value={settings.announcement_title||''} onChange={e=>setSettings({...settings,announcement_title:e.target.value})}/></label><label>Pesan maintenance<textarea value={settings.maintenance_message||''} onChange={e=>setSettings({...settings,maintenance_message:e.target.value})}/></label><label>Pesan announcement<textarea value={settings.announcement_message||''} onChange={e=>setSettings({...settings,announcement_message:e.target.value})}/></label></div><div className="admin-actions"><button className="btn">Simpan Pengaturan</button></div></form>}</section>
  <section className="admin-section"><div className="admin-title"><div><div className="kicker">Search & Filter</div><h2>Pengguna & Household</h2></div></div><div className="admin-filter"><input placeholder="Cari nama, email, atau household…" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Semua status</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="suspended">Suspended</option></select></div></section>
  <section className="admin-section"><div className="admin-title"><div><div className="kicker">Accounts</div><h2>Akun Pengguna</h2></div><span>{filteredProfiles.length} akun</span></div><div className="admin-table-wrap"><table><thead><tr><th>Pengguna</th><th>Status</th><th>Buat Household</th><th>Household</th><th>Aksi</th></tr></thead><tbody>{filteredProfiles.map(p=>{const ms=members.filter(m=>m.user_id===p.id);return <tr key={p.id}><td><b>{p.display_name||p.email||'Tanpa nama'}</b><div className="muted small">{p.email}</div></td><td><span className={`admin-pill ${p.status}`}>{p.status}</span></td><td>{p.can_create_household?'Diizinkan':'Tidak'}</td><td>{ms.map(m=>houses.find(h=>h.id===m.household_id)?.name).filter(Boolean).join(', ')||'—'}</td><td><div className="admin-actions">{p.status!=='approved'&&<button className="btn" onClick={()=>patchProfile(p.id,{status:'approved'},'Akun disetujui.')}>Setujui</button>}<button className="btn alt" onClick={()=>patchProfile(p.id,{can_create_household:!p.can_create_household},p.can_create_household?'Izin household dicabut.':'Izin household diberikan.')}>{p.can_create_household?'Cabut Izin':'Izinkan Household'}</button>{p.status!=='suspended'&&<button className="icon danger" onClick={()=>patchProfile(p.id,{status:'suspended',can_create_household:false},'Akun dinonaktifkan.')}>Nonaktifkan</button>}</div></td></tr>})}</tbody></table></div></section>
  <section className="admin-section"><div className="admin-title"><div><div className="kicker">Households</div><h2>Semua Household</h2></div><span>{filteredHouses.length} household</span></div><div className="admin-grid">{filteredHouses.map(h=>{const ms=members.filter(m=>m.household_id===h.id);return <article className="admin-card" key={h.id}><div className="admin-card-head"><div><h3>{h.name}</h3><span className={`admin-pill ${h.status}`}>{h.status}</span></div><button className="btn alt" onClick={()=>viewFinance(h.id)}>Lihat Keuangan</button></div><p className="muted small">Dibuat oleh: {profileMap[h.created_by]?.display_name||profileMap[h.created_by]?.email||h.created_by}</p><div className="member-list">{ms.map(m=><div key={m.user_id}><span><b>{profileMap[m.user_id]?.display_name||profileMap[m.user_id]?.email||m.user_id}</b> · {m.role}</span>{m.role!=='owner'&&<button className="icon" onClick={()=>removeMember(h.id,m.user_id)}>Cabut</button>}</div>)}</div><div className="admin-actions">{h.status!=='active'&&<button className="btn" onClick={()=>patchHouse(h.id,'active')}>Aktifkan</button>}{h.status!=='suspended'&&<button className="btn alt" onClick={()=>patchHouse(h.id,'suspended')}>Suspend</button>}<button className="icon danger" onClick={()=>deleteHouse(h)}>Hapus Permanen</button></div></article>})}</div></section>
  {selectedHouse&&<section className="admin-section"><div className="admin-title"><div><div className="kicker">Read-only Finance</div><h2>{selectedHouse.name}</h2></div><button className="icon" onClick={()=>{setSelected('');setFinance({})}}>Tutup</button></div>{financeLoading?<div className="admin-card">Memuat data…</div>:<><div className="admin-metrics"><div><span>Total Income</span><b>{rp(totalIncome)}</b></div><div><span>Total Expenses</span><b>{rp(totalExpenses)}</b></div><div><span>Cashflow</span><b>{rp(totalIncome-totalExpenses)}</b></div><div><span>Tabungan</span><b>{rp(savingValue)}</b></div><div><span>Sisa Hutang</span><b>{rp(debtRemaining)}</b></div></div><div className="admin-card"><h3>Data Household</h3><div className="admin-fin-row"><span>Income</span><b>{(finance.income||[]).length}</b></div><div className="admin-fin-row"><span>Expenses</span><b>{(finance.expenses||[]).length}</b></div><div className="admin-fin-row"><span>Budget</span><b>{(finance.budgets||[]).length}</b></div><div className="admin-fin-row"><span>Wishlist</span><b>{(finance.wishlists||[]).length}</b></div></div></>}</section>}
  <section className="admin-section"><div className="admin-title"><div><div className="kicker">Security Activity</div><h2>Aktivitas Terbaru</h2></div><span>{events.length} event</span></div><div className="admin-card admin-events">{events.length===0?<p className="empty">Belum ada event.</p>:events.slice(0,20).map(e=><div key={e.id}><div><b>{e.event_type}</b><small>{new Date(e.created_at).toLocaleString('id-ID')}</small></div><code>{e.detail&&Object.keys(e.detail).length?JSON.stringify(e.detail):'—'}</code></div>)}</div></section><Toast message={toast} onDone={()=>setToast('')}/>
 </main>
}
