'use client';
import {FormEvent,useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {ConfirmDialog} from '@/app/components/UiKit';
export default function MusicAdmin(){
 const[deleting,setDeleting]=useState<any>(null);
 async function remove(){if(!deleting||busy)return;setBusy(true);setMsg('');try{
 const r=await supabase.from('music_tracks').delete().eq('id',deleting.id).select('id').single();if(r.error)throw r.error;
 const prefix=supabase.storage.from('vault-music').getPublicUrl('').data.publicUrl;
 let warning='';if(deleting.url.startsWith(prefix)){const key=deleting.url.slice(prefix.length);if(key&&!key.includes('/')&&!key.includes('..')){const s=await supabase.storage.from('vault-music').remove([key]);if(s.error)warning=' File penyimpanan belum terhapus: '+s.error.message;}}
 setDeleting(null);await load();setMsg('Lagu dihapus dari daftar.'+warning);window.dispatchEvent(new Event('fv-music-refresh'));
 }catch(e){setMsg(e instanceof Error?e.message:'Gagal menghapus lagu')}finally{setBusy(false)}}
 const[tracks,setTracks]=useState<any[]>([]),[settings,setSettings]=useState<any>(null),[title,setTitle]=useState(''),[artist,setArtist]=useState(''),[url,setUrl]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function load(){const[a,b]=await Promise.all([supabase.from('music_tracks').select('*').order('sort_order').order('created_at'),supabase.from('music_settings').select('*').single()]);if(a.error||b.error){setMsg(a.error?.message||b.error?.message||'Gagal memuat');return}setTracks(a.data||[]);setSettings(b.data)}
 useEffect(()=>{void load()},[]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;setBusy(true);setMsg('');let path='';try{
 let audioUrl=url.trim();if(file){if(!file.name.toLowerCase().endsWith('.mp3')||file.size>20*1024*1024)throw Error('Gunakan MP3 maksimal 20 MB.');path=crypto.randomUUID()+'.mp3';const r=await supabase.storage.from('vault-music').upload(path,file,{contentType:'audio/mpeg'});if(r.error)throw r.error;audioUrl=supabase.storage.from('vault-music').getPublicUrl(path).data.publicUrl;}
 if(!audioUrl.startsWith('https://'))throw Error('Masukkan URL audio HTTPS langsung atau unggah MP3.');
 const r=await supabase.from('music_tracks').insert({title:title.trim(),artist:artist.trim(),url:audioUrl,sort_order:tracks.length}).select('id').single();if(r.error)throw r.error;
 setTitle('');setArtist('');setUrl('');setFile(null);form.reset();await load();setMsg('Lagu ditambahkan.');
 }catch(e){if(path)await supabase.storage.from('vault-music').remove([path]);setMsg(e instanceof Error?e.message:'Gagal menambah lagu')}finally{setBusy(false)}}
 async function save(){setBusy(true);setMsg('');try{const r=await supabase.from('music_settings').update({enabled:settings.enabled,mode:settings.mode,daily_track_id:settings.daily_track_id||null}).eq('id',true).select('id').single();if(r.error)throw r.error;setMsg('Pengaturan musik tersimpan.');window.dispatchEvent(new Event('fv-music-refresh'))}catch(e){setMsg(e instanceof Error?e.message:'Gagal menyimpan')}finally{setBusy(false)}}
 async function toggle(t:any){setBusy(true);const r=await supabase.from('music_tracks').update({enabled:!t.enabled}).eq('id',t.id).select('id').single();if(r.error)setMsg(r.error.message);else await load();setBusy(false);window.dispatchEvent(new Event('fv-music-refresh'))}
 return <section className="admin-section"><h2>Musik Family Vault</h2><div className="admin-card">{msg&&<p role="status">{msg}</p>}{settings&&<><label><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/> Aktifkan musik untuk pengguna</label><label>Mode<select value={settings.mode} onChange={e=>setSettings({...settings,mode:e.target.value})}><option value="daily">Music of the Day</option><option value="playlist">Putar semua lagu berurutan dan ulangi</option></select></label><label>Lagu pilihan hari ini<select value={settings.daily_track_id||''} onChange={e=>setSettings({...settings,daily_track_id:e.target.value})}><option value="">Lagu aktif pertama</option>{tracks.filter(t=>t.enabled).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><button className="btn" disabled={busy} onClick={save}>Simpan Pengaturan Musik</button></>}<hr/><form onSubmit={add}><h3>Tambah lagu</h3><label>Judul<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Penyanyi<input value={artist} onChange={e=>setArtist(e.target.value)}/></label><label>URL audio langsung<input type="url" placeholder="https://.../lagu.mp3" value={url} onChange={e=>setUrl(e.target.value)} disabled={!!file}/></label><label>Atau unggah MP3 (maks. 20 MB)<input type="file" accept=".mp3,audio/mpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="btn" disabled={busy}>Tambah Lagu</button></form><h3>Daftar lagu</h3>{tracks.map(t=><div key={t.id} className="admin-fin-row"><span>{t.title} — {t.artist||'Tanpa penyanyi'}</span><button className="btn alt" disabled={busy} onClick={()=>setDeleting(t)}>Hapus</button><button className="btn alt" disabled={busy} onClick={()=>toggle(t)}>{t.enabled?'Nonaktifkan':'Aktifkan'}</button></div>)}</div><ConfirmDialog open={!!deleting} title="Hapus lagu?" message={'Hapus '+(deleting?.title||'lagu ini')+' dari daftar musik?'} detail="File MP3 unggahan juga dihapus. Lagu dari URL hanya dihapus dari daftar." busy={busy} onClose={()=>setDeleting(null)} onConfirm={remove}/></section>
}

