'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {supabase} from '@/lib/supabase';
import SessionGuard from '@/app/components/SessionGuard';
import {Toast} from '@/app/components/UiKit';

type R=Record<string,any>;
export default function ProfilePage(){
 const router=useRouter();const[loading,setLoading]=useState(true),[user,setUser]=useState<R|null>(null),[profile,setProfile]=useState<R|null>(null),[houses,setHouses]=useState<R[]>([]),[members,setMembers]=useState<R[]>([]),[admin,setAdmin]=useState(false),[name,setName]=useState(''),[toast,setToast]=useState(''),[err,setErr]=useState('');
 async function reload(){const{data}=await supabase.auth.getUser();if(!data.user){router.replace('/login');return}setUser(data.user);const[p,h,m,a]=await Promise.all([supabase.from('profiles').select('*').eq('id',data.user.id).maybeSingle(),supabase.from('households').select('id,name,status').order('created_at'),supabase.from('household_members').select('*').eq('user_id',data.user.id),supabase.from('platform_admins').select('role').eq('user_id',data.user.id).maybeSingle()]);if(p.error){setErr(p.error.message)}else{setProfile(p.data);setName(p.data?.display_name||'')}setHouses(h.data||[]);setMembers(m.data||[]);setAdmin(!!a.data);setLoading(false)}
 useEffect(()=>{reload()},[]);
 async function save(e:FormEvent){e.preventDefault();const r=await supabase.from('profiles').update({display_name:name.trim()||null}).eq('id',user.id);if(r.error)setErr(r.error.message);else{setToast('Profil berhasil diperbarui.');reload()}}
 async function signOut(){await supabase.auth.signOut();router.replace('/login')}
 if(loading)return <main className="center"><div className="auth-card">Memuat profil…</div></main>;
 return <main className="profile-shell"><SessionGuard minutes={60}/><header className="profile-head"><div><Link href="/dashboard" className="back">← Dashboard</Link><div className="kicker">Account</div><h1>Profil & Akun</h1><p className="muted">Kelola identitas, household, dan keamanan akun Family Vault.</p></div><div className="profile-actions"><Link className="btn alt" href="/security">🔐 Security Center</Link>{admin&&<Link className="btn alt" href="/admin">🛡️ Admin</Link>}<button className="icon" onClick={signOut}>Keluar</button></div></header>{err&&<div className="status error">{err}</div>}<section className="profile-grid"><article className="card pad"><div className="kicker">Identity</div><h2>Informasi akun</h2><form onSubmit={save}><label>Nama tampilan<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nama yang tampil di history"/></label><label>Email<input value={user?.email||''} disabled/></label><button className="btn">Simpan Profil</button></form></article><article className="card pad"><div className="kicker">Access</div><h2>Status akses</h2><div className="profile-row"><span>Status akun</span><b>{profile?.status||'—'}</b></div><div className="profile-row"><span>Boleh buat household</span><b>{profile?.can_create_household?'Ya':'Tidak'}</b></div><div className="profile-row"><span>Role platform</span><b>{admin?'Admin':'User'}</b></div><div className="profile-row"><span>Email verified</span><b>{user?.email_confirmed_at?'Ya':'Belum'}</b></div></article></section><section className="card pad"><div className="kicker">Households</div><h2>Household yang dapat diakses</h2><div className="profile-house-list">{members.length===0?<p className="empty">Belum tergabung ke household.</p>:members.map(m=>{const h=houses.find(x=>x.id===m.household_id);return <div key={m.household_id}><div><b>{h?.name||m.household_id}</b><small>{m.role} · {h?.status||'unknown'}</small></div><span className="badge done">{m.role}</span></div>})}</div></section><Toast message={toast} onDone={()=>setToast('')}/></main>
}
