'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {supabase} from '@/lib/supabase';
import {Toast} from '@/app/components/UiKit';
type R=Record<string,any>;

export default function FeedbackPage(){
 const router=useRouter();
 const[uid,setUid]=useState(''),[houses,setHouses]=useState<R[]>([]),[hid,setHid]=useState(''),[category,setCategory]=useState('suggestion'),[message,setMessage]=useState(''),[rows,setRows]=useState<R[]>([]),[busy,setBusy]=useState(true),[sending,setSending]=useState(false),[err,setErr]=useState(''),[toast,setToast]=useState('');
 async function load(){const{data:u}=await supabase.auth.getUser();if(!u.user){router.replace('/login');return}setUid(u.user.id);const[h,f]=await Promise.all([supabase.from('households').select('id,name').eq('status','active').order('created_at'),supabase.from('app_feedback').select('*').eq('user_id',u.user.id).order('created_at',{ascending:false})]);if(h.error||f.error)setErr(h.error?.message||f.error?.message||'Gagal memuat');else{setHouses(h.data||[]);setHid(h.data?.[0]?.id||'');setRows(f.data||[])}setBusy(false)}
 useEffect(()=>{load()},[]);
 async function submit(e:FormEvent){e.preventDefault();if(message.trim().length<3)return;setSending(true);setErr('');const r=await supabase.from('app_feedback').insert({user_id:uid,household_id:hid||null,category,message:message.trim()});setSending(false);if(r.error)setErr(r.error.message);else{setMessage('');setToast('Saran atau kritik berhasil dikirim ke admin.');await load()}}
 if(busy)return <main className="center"><section className="auth-card"><div className="logo">Family Vault</div><p>Memuat kotak saran…</p></section></main>;
 return <main className="feedback-shell"><header className="feedback-head"><div><div className="kicker">Feedback</div><h1>Saran & Kritik</h1><p className="muted">Kirim ide fitur, kritik, atau laporan masalah langsung ke admin Family Vault.</p></div><Link className="btn alt" href="/dashboard">← Dashboard</Link></header>{err&&<div className="status error">{err}</div>}<section className="feedback-grid"><form className="card pad feedback-form" onSubmit={submit}><h2>Kirim masukan</h2><label>Household<select value={hid} onChange={e=>setHid(e.target.value)}><option value="">Tidak spesifik household</option>{houses.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><label>Jenis<select value={category} onChange={e=>setCategory(e.target.value)}><option value="suggestion">Saran fitur</option><option value="criticism">Kritik</option><option value="bug">Laporan masalah / bug</option><option value="other">Lainnya</option></select></label><label>Pesan<textarea rows={7} value={message} onChange={e=>setMessage(e.target.value)} maxLength={4000} placeholder="Ceritakan saran atau masalahnya dengan jelas…" required/></label><div className="feedback-submit"><small className="muted">{message.length}/4000</small><button className="btn" disabled={sending||message.trim().length<3}>{sending?'Mengirim…':'Kirim ke Admin'}</button></div></form><section className="card pad"><div className="panel-line"><div><div className="kicker">Riwayat</div><h2>Masukan saya</h2></div><span className="muted">{rows.length}</span></div>{rows.length===0?<p className="empty">Belum ada masukan yang dikirim.</p>:<div className="feedback-list">{rows.map(x=><article className="feedback-item" key={x.id}><div className="feedback-item-head"><span className={`badge ${x.status==='resolved'||x.status==='closed'?'done':'pending'}`}>{statusLabel(x.status)}</span><small>{new Date(x.created_at).toLocaleString('id-ID')}</small></div><b>{categoryLabel(x.category)}</b><p>{x.message}</p>{x.admin_note&&<div className="feedback-admin-note"><strong>Catatan admin</strong><p>{x.admin_note}</p></div>}</article>)}</div>}</section></section><Toast message={toast} onDone={()=>setToast('')}/></main>}
function categoryLabel(v:string){return({suggestion:'Saran fitur',criticism:'Kritik',bug:'Laporan masalah',other:'Lainnya'} as Record<string,string>)[v]||v}
function statusLabel(v:string){return({new:'Baru',reviewing:'Ditinjau',planned:'Direncanakan',resolved:'Selesai',closed:'Ditutup'} as Record<string,string>)[v]||v}
