'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {supabase} from '@/lib/supabase';
import QuickAddModal,{QuickAddKind} from './QuickAddModal';
import {AnnouncementBanner,BarChart,LineChart,Toast} from '@/app/components/UiKit';

type R=Record<string,any>;
const NAV=['Dashboard','Finance','Investasi','Tabungan','Hutang','Wishlist','Otomatis','Arsip'];
const FT=['Income','Expenses','Budgeting','Kewajiban'];
const IT=['ETF','Emas','Dividen'];
const rp=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const num=(n:number)=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:6}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const sum=(a:R[],field='amount')=>a.reduce((s,x)=>s+Number(x[field]||0),0);
function keyFor(s:string){const d=new Date(s+'T00:00:00');let y=d.getFullYear(),m=d.getMonth();if(d.getDate()<22){m--;if(m<0){m=11;y--}}return`${y}-${String(m+1).padStart(2,'0')}`}
function bounds(k:string){const[y,m]=k.split('-').map(Number),a=new Date(y,m-1,22),e=new Date(y,m,22),l=new Date(e);l.setDate(l.getDate()-1);const z=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return{start:z(a),end:z(e),last:z(l)}}
function periodLabel(k:string){const b=bounds(k),f=new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric'});return`${f.format(new Date(b.start+'T00:00:00'))} – ${f.format(new Date(b.last+'T00:00:00'))}`}
function nextPeriod(k:string,offset:number){const[y,m]=k.split('-').map(Number),d=new Date(y,m-1+offset,1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function fmtShort(k:string){const[y,m]=k.split('-').map(Number);return new Intl.DateTimeFormat('id-ID',{month:'short',year:'2-digit'}).format(new Date(y,m-1,1))}
function csvCell(v:any){const s=String(v??'').replace(/"/g,'""');return`"${s}"`}
function downloadCsv(name:string,rows:any[][]){const text=rows.map(r=>r.map(csvCell).join(',')).join('\n');const blob=new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}

export default function DashboardAppV2(){
 const router=useRouter();
 const[uid,setUid]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(true),[err,setErr]=useState('');
 const[houses,setHouses]=useState<R[]>([]),[hid,setHid]=useState(''),[active,setActive]=useState('Dashboard'),[ft,setFt]=useState('Income'),[it,setIt]=useState('ETF'),[period,setPeriod]=useState(keyFor(today()));
 const[income,setIncome]=useState<R[]>([]),[expenses,setExpenses]=useState<R[]>([]),[budgets,setBudgets]=useState<R[]>([]),[obligations,setObligations]=useState<R[]>([]),[etfs,setEtfs]=useState<R[]>([]),[etfTx,setEtfTx]=useState<R[]>([]),[golds,setGolds]=useState<R[]>([]),[goldTx,setGoldTx]=useState<R[]>([]),[stocks,setStocks]=useState<R[]>([]),[stockTx,setStockTx]=useState<R[]>([]),[divs,setDivs]=useState<R[]>([]),[savings,setSavings]=useState<R[]>([]),[savingTx,setSavingTx]=useState<R[]>([]),[debts,setDebts]=useState<R[]>([]),[debtPay,setDebtPay]=useState<R[]>([]),[wishes,setWishes]=useState<R[]>([]),[parts,setParts]=useState<R[]>([]),[recurring,setRecurring]=useState<R[]>([]),[snapshots,setSnapshots]=useState<R[]>([]),[closings,setClosings]=useState<R[]>([]),[archived,setArchived]=useState<R[]>([]);
 const[settings,setSettings]=useState<R|null>(null),[hideAnnouncement,setHideAnnouncement]=useState(false),[quick,setQuick]=useState<QuickAddKind|null>(null),[toast,setToast]=useState(''),[toastTone,setToastTone]=useState<'success'|'error'|'info'>('success');
 const b=bounds(period),inside=(d:string)=>!!d&&d>=b.start&&d<b.end;
 async function top(t:string,id:string){const r=await supabase.from(t).select('*').eq('household_id',id).is('archived_at',null).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
 async function child(t:string,c:string,ids:string[]){if(!ids.length)return[];const r=await supabase.from(t).select('*').in(c,ids).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
 async function loadArchive(id:string){const tables=['income','expenses','budgets','obligations','etf_assets','gold_assets','dividend_stocks','savings','debts','wishlists'];const all:R[]=[];for(const t of tables){const r=await supabase.from(t).select('*').eq('household_id',id).not('archived_at','is',null).order('archived_at',{ascending:false}).limit(20);if(!r.error)all.push(...(r.data||[]).map(x=>({...x,_table:t,_label:x.name||x.source||x.category||x.ticker||t})))}setArchived(all.sort((a,c)=>new Date(c.archived_at).getTime()-new Date(a.archived_at).getTime()))}
 async function load(id:string){setBusy(true);setErr('');try{const[a,c,d,e,f,g,h,i,j,k,rr,ss,cc]=await Promise.all([top('income',id),top('expenses',id),top('budgets',id),top('obligations',id),top('etf_assets',id),top('gold_assets',id),top('dividend_stocks',id),top('savings',id),top('debts',id),top('wishlists',id),top('recurring_transactions',id),supabase.from('portfolio_snapshots').select('*').eq('household_id',id).order('snapshot_date',{ascending:true}).limit(30),supabase.from('monthly_closings').select('*').eq('household_id',id).order('period_start',{ascending:false}).limit(12)]);setIncome(a);setExpenses(c);setBudgets(d);setObligations(e);setEtfs(f);setGolds(g);setStocks(h);setSavings(i);setDebts(j);setWishes(k);setRecurring(rr);setSnapshots(ss.data||[]);setClosings(cc.data||[]);const[l,m,n,o,p,q,r]=await Promise.all([child('etf_transactions','asset_id',f.map(x=>x.id)),child('gold_transactions','asset_id',g.map(x=>x.id)),child('dividend_stock_transactions','stock_id',h.map(x=>x.id)),child('dividends','stock_id',h.map(x=>x.id)),child('saving_transactions','saving_id',i.map(x=>x.id)),child('debt_payments','debt_id',j.map(x=>x.id)),child('wishlist_parts','wishlist_id',k.map(x=>x.id))]);setEtfTx(l);setGoldTx(m);setStockTx(n);setDivs(o);setSavingTx(p);setDebtPay(q);setParts(r);await loadArchive(id)}catch(ex:any){setErr(ex.message||'Gagal memuat data')}finally{setBusy(false)}}
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getUser();if(!data.user){router.replace('/login');return}setUid(data.user.id);setEmail(data.user.email||'');const[h,s]=await Promise.all([supabase.from('households').select('id,name,status').eq('status','active').order('created_at'),supabase.from('platform_settings').select('*').eq('id',true).maybeSingle()]);if(h.error){setErr(h.error.message);setBusy(false);return}setHouses(h.data||[]);setSettings(s.data||null);const first=h.data?.[0];if(first){setHid(first.id);await load(first.id)}else setBusy(false)})()},[router]);
 useEffect(()=>{const onFinanceChanged=(event:Event)=>{if((event as CustomEvent).detail?.householdId===hid)void load(hid)};window.addEventListener("fv-finance-changed",onFinanceChanged);return()=>window.removeEventListener("fv-finance-changed",onFinanceChanged)},[hid]);
 async function refresh(message?:string){if(hid)await load(hid);if(message){setToastTone('success');setToast(message)}}
 async function archiveItem(table:string,id:string,label:string){if(!confirm(`Arsipkan ${label}? Data tidak dihapus permanen.`))return;const r=await supabase.from(table).update({archived_at:new Date().toISOString()}).eq('id',id);if(r.error){setToastTone('error');setToast(r.error.message)}else refresh(`${label} dipindahkan ke Arsip.`)}
 async function restoreItem(x:R){const r=await supabase.from(x._table).update({archived_at:null}).eq('id',x.id);if(r.error){setToastTone('error');setToast(r.error.message)}else refresh(`${x._label} dipulihkan.`)}
 async function logout(){await supabase.auth.signOut();router.replace('/login')}

 const pi=income.filter(x=>inside(x.happened_at)),pe=expenses.filter(x=>inside(x.happened_at)),pbud=budgets.filter(x=>x.period_start===b.start),pob=obligations.filter(x=>inside(x.due_date));
 const etfM=(a:R)=>{const tx=etfTx.filter(x=>x.asset_id===a.id),buy=sum(tx.filter(x=>x.type==='buy')),sell=sum(tx.filter(x=>x.type==='sell')),invested=Math.max(0,buy-sell),value=Number(a.current_value||0)||invested;return{invested,value,pl:value-invested}};
 const goldM=(a:R)=>{const tx=goldTx.filter(x=>x.asset_id===a.id),buy=tx.filter(x=>x.type==='buy'),sell=tx.filter(x=>x.type==='sell'),grams=Math.max(0,buy.reduce((s,x)=>s+Number(x.grams||0),0)-sell.reduce((s,x)=>s+Number(x.grams||0),0)),invested=sum(buy),proceeds=sum(sell),value=grams*Number(a.current_price_per_gram||0);return{grams,invested,value,pl:value+proceeds-invested}};
 const stockM=(a:R)=>{const tx=stockTx.filter(x=>x.stock_id===a.id),buy=tx.filter(x=>x.type==='buy'),sell=tx.filter(x=>x.type==='sell'),units=Math.max(0,buy.reduce((s,x)=>s+Number(x.units||0),0)-sell.reduce((s,x)=>s+Number(x.units||0),0)),invested=sum(buy),proceeds=sum(sell),value=units*Number(a.current_price||0),div=sum(divs.filter(x=>x.stock_id===a.id));return{units,invested,value,div,pl:value+proceeds+div-invested}};
 const saved=(id:string)=>sum(savingTx.filter(x=>x.saving_id===id)),debtLeft=(d:R)=>Math.max(0,Number(d.original_amount||0)-sum(debtPay.filter(x=>x.debt_id===d.id)));
 const ti=sum(pi),te=sum(pe),left=ti-te,totalDebt=debts.reduce((s,d)=>s+debtLeft(d),0),totalETF=etfs.reduce((s,a)=>s+etfM(a).value,0),totalGold=golds.reduce((s,a)=>s+goldM(a).value,0),totalStock=stocks.reduce((s,a)=>s+stockM(a).value,0),totalSav=savings.reduce((s,a)=>s+saved(a.id),0),investments=totalETF+totalGold+totalStock,netWorth=investments+totalSav-totalDebt,savingsRate=ti?Math.max(0,(ti-te)/ti*100):0;
 const biggestCat=useMemo(()=>{const m:Record<string,number>={};for(const x of pe)m[x.category||'Lainnya']=(m[x.category||'Lainnya']||0)+Number(x.amount||0);return Object.entries(m).sort((a,c)=>c[1]-a[1])[0]},[pe]);
 const upcoming=useMemo(()=>obligations.filter(x=>x.status!=='sudah'&&x.due_date>=today()).sort((a,c)=>a.due_date.localeCompare(c.due_date))[0],[obligations]);
 const chartRows=useMemo(()=>Array.from({length:6},(_,i)=>{const k=nextPeriod(period,i-5),bb=bounds(k),ins=(d:string)=>d>=bb.start&&d<bb.end;return{label:fmtShort(k),income:sum(income.filter(x=>ins(x.happened_at))),expense:sum(expenses.filter(x=>ins(x.happened_at)))}}),[period,income,expenses]);
 useEffect(()=>{if(!hid||busy)return;supabase.from('portfolio_snapshots').upsert({household_id:hid,snapshot_date:today(),net_worth:netWorth,savings_total:totalSav,investment_total:investments,debt_total:totalDebt},{onConflict:'household_id,snapshot_date'}).then(()=>{})},[hid,busy,netWorth,totalSav,investments,totalDebt]);
 async function switchHouse(id:string){setHid(id);await load(id)}
 async function closeMonth(){const note=window.confirm('Tutup periode ini? Ringkasan akan disimpan sebagai monthly closing.');if(!note)return;const r=await supabase.from('monthly_closings').upsert({household_id:hid,period_start:b.start,period_end:b.last,income_total:ti,expense_total:te,savings_total:totalSav,net_worth:netWorth,note:null,closed_by:uid},{onConflict:'household_id,period_start'});if(r.error){setToastTone('error');setToast(r.error.message)}else refresh('Periode berhasil ditutup dan disimpan.')}
 async function runRecurring(){const due=recurring.filter(x=>x.active&&x.next_run<=today());if(!due.length){setToastTone('info');setToast('Belum ada transaksi berulang yang jatuh tempo.');return}let count=0;for(const x of due){let r:any;if(x.kind==='income')r=await supabase.from('income').insert({household_id:hid,source:x.name,amount:x.amount,happened_at:x.next_run,note:'Recurring',created_by:uid});else if(x.kind==='expense')r=await supabase.from('expenses').insert({household_id:hid,name:x.name,category:x.category||'Recurring',amount:x.amount,happened_at:x.next_run,note:'Recurring',created_by:uid});else if(x.kind==='obligation')r=await supabase.from('obligations').insert({household_id:hid,name:x.name,amount:x.amount,status:'belum',due_date:x.next_run,note:'Recurring',created_by:uid});else if(x.kind==='saving'&&x.target_id)r=await supabase.from('saving_transactions').insert({saving_id:x.target_id,amount:x.amount,happened_at:x.next_run,created_by:uid});if(r?.error)continue;const d=new Date(x.next_run+'T00:00:00');if(x.frequency==='weekly')d.setDate(d.getDate()+7);else if(x.frequency==='yearly')d.setFullYear(d.getFullYear()+1);else d.setMonth(d.getMonth()+1);await supabase.from('recurring_transactions').update({next_run:d.toISOString().slice(0,10)}).eq('id',x.id);count++}await refresh(`${count} transaksi berulang diproses.`)}
 function exportData(){const rows:any[][]=[['Tipe','Tanggal','Nama','Kategori','Nominal','Catatan'],...income.map(x=>['Income',x.happened_at,x.source,'',x.amount,x.note||'']),...expenses.map(x=>['Expense',x.happened_at,x.name,x.category,x.amount,x.note||'']),...obligations.map(x=>['Kewajiban',x.due_date,x.name,x.status,x.amount,x.note||''])];downloadCsv(`family-vault-${period}.csv`,rows)}
 async function saveAsset(table:string,id:string,patch:R){const r=await supabase.from(table).update(patch).eq('id',id);if(r.error){setToastTone('error');setToast(r.error.message)}else refresh('Nilai aset diperbarui.')}

 if(busy&&income.length===0)return <main className="center"><section className="auth-card"><div className="logo">Family Vault</div><p>Menyiapkan vault keluarga…</p></section></main>;
 const qa=(k:QuickAddKind)=>setQuick(k);
 const currentHouse=houses.find(x=>x.id===hid);
 return <div className="shell refined-shell">
  <aside className="sidebar refined-sidebar"><div><div className="logo">Family Vault</div><div className="side-muted">{currentHouse?.name||'Household'}</div></div><nav>{NAV.map(n=><button key={n} className={active===n?'nav-active':''} onClick={()=>setActive(n)}>{n}</button>)}</nav><div className="side-bottom"><Link href="/family">👥 Keluarga</Link><Link href="/profile">👤 Profil</Link><Link href="/security">🔐 Keamanan</Link><button onClick={logout}>Keluar</button></div></aside>
  <main className="content refined-content">
   {settings?.announcement_enabled&&!hideAnnouncement&&<AnnouncementBanner title={settings.announcement_title} message={settings.announcement_message} onClose={()=>setHideAnnouncement(true)}/>} 
   <header className="fv-top refined-top"><div><div className="kicker">{active}</div><h1>{active==='Dashboard'?'Ringkasan Keluarga':active}</h1><p className="muted">{periodLabel(period)}</p></div><div className="fv-actions"><select value={hid} onChange={e=>switchHouse(e.target.value)}>{houses.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select><div className="period-picker"><span>Periode</span><input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></div><button className="btn alt" onClick={exportData}>Export CSV</button><button className="btn" onClick={()=>qa('expense')}>＋ Tambah</button></div></header>
   {err&&<div className="status error">{err}</div>}

   {active==='Dashboard'&&<>
    <section className="grid5"><div className="card stat"><span>Income</span><strong>{rp(ti)}</strong><small>periode aktif</small></div><div className="card stat"><span>Expenses</span><strong>{rp(te)}</strong><small>{pe.length} transaksi</small></div><div className="card stat"><span>Sisa Cashflow</span><strong className={left>=0?'positive':'negative'}>{rp(left)}</strong><small>{savingsRate.toFixed(1)}% savings rate</small></div><div className="card stat"><span>Net Worth</span><strong>{rp(netWorth)}</strong><small>aset - hutang</small></div><div className="card stat"><span>Sisa Hutang</span><strong>{rp(totalDebt)}</strong><small>{debts.length} akun</small></div></section>
    <section className="insight-grid gap-top"><div className="card pad"><div className="kicker">Insight</div><h2>Pengeluaran terbesar</h2><div className="big">{biggestCat?biggestCat[0]:'—'}</div><p className="muted">{biggestCat?rp(biggestCat[1]):'Belum ada expense di periode ini.'}</p></div><div className="card pad"><div className="kicker">Upcoming</div><h2>Kewajiban berikutnya</h2><div className="big">{upcoming?.name||'—'}</div><p className="muted">{upcoming?`${upcoming.due_date} · ${rp(upcoming.amount)}`:'Tidak ada kewajiban mendatang.'}</p></div><div className="card pad"><div className="kicker">Portfolio</div><h2>Total aset produktif</h2><div className="big">{rp(investments+totalSav)}</div><p className="muted">Investasi {rp(investments)} · Tabungan {rp(totalSav)}</p></div></section>
    <section className="grid2 gap-top"><div className="card pad"><div className="card-head"><div><div className="kicker">Cashflow Trend</div><h2>Income vs Expenses</h2></div><button className="icon" onClick={closeMonth}>Tutup Periode</button></div><BarChart rows={chartRows}/></div><div className="card pad"><div className="kicker">Net Worth History</div><h2>Perkembangan Kekayaan Bersih</h2><LineChart rows={snapshots.slice(-12).map(x=>({label:new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short'}).format(new Date(x.snapshot_date+'T00:00:00')),value:Number(x.net_worth||0)}))}/></div></section>
    <section className="grid2 gap-top"><div className="card pad"><div className="kicker">Investasi</div><h2>Komposisi aset</h2><div className="asset-list"><div><span>ETF</span><b>{rp(totalETF)}</b></div><div><span>Emas</span><b>{rp(totalGold)}</b></div><div><span>Saham Dividen</span><b>{rp(totalStock)}</b></div><div><span>Tabungan</span><b>{rp(totalSav)}</b></div></div></div><div className="card pad"><div className="kicker">Monthly Closing</div><h2>Periode tersimpan</h2>{closings.length===0?<p className="empty">Belum ada closing.</p>:closings.slice(0,5).map(x=><div className="panel-line" key={x.id}><span>{x.period_start}</span><b>{rp(Number(x.income_total)-Number(x.expense_total))}</b></div>)}</div></section>
   </>}

   {active==='Finance'&&<><div className="tabs">{FT.map(x=><button key={x} className={ft===x?'active':''} onClick={()=>setFt(x)}>{x}</button>)}</div>{ft==='Income'&&<section className="card pad"><div className="panel-line"><h2>Income</h2><button className="btn" onClick={()=>qa('income')}>＋ Income</button></div><Table rows={pi} columns={[['happened_at','Tanggal'],['source','Sumber'],['amount','Nominal']]} money="amount" action={x=><button className="icon" onClick={()=>archiveItem('income',x.id,x.source)}>Arsip</button>}/></section>}{ft==='Expenses'&&<section className="card pad"><div className="panel-line"><h2>Expenses</h2><button className="btn" onClick={()=>qa('expense')}>＋ Expense</button></div><Table rows={pe} columns={[['happened_at','Tanggal'],['name','Keperluan'],['category','Kategori'],['amount','Nominal']]} money="amount" action={x=><button className="icon" onClick={()=>archiveItem('expenses',x.id,x.name)}>Arsip</button>}/></section>}{ft==='Budgeting'&&<section><div className="panel-line"><h2>Budgeting</h2><button className="btn" onClick={()=>qa('budget')}>＋ Budget</button></div><div className="budget-grid">{pbud.map(x=>{const auto=sum(pe.filter(e=>(e.category||'').toLowerCase()===(x.category||'').toLowerCase())),used=x.manual_used??auto,p=Number(x.amount)?Math.min(100,Number(used)/Number(x.amount)*100):0;return <div className="card pad" key={x.id}><div className="card-head"><b>{x.category}</b><button className="icon" onClick={()=>archiveItem('budgets',x.id,x.category)}>Arsip</button></div><p>{rp(used)} / {rp(x.amount)}</p><div className="progress"><div style={{width:`${p}%`}}/></div></div>})}</div></section>}{ft==='Kewajiban'&&<section className="card pad"><div className="panel-line"><h2>Kewajiban</h2><button className="btn" onClick={()=>qa('obligation')}>＋ Kewajiban</button></div><Table rows={pob} columns={[['due_date','Jatuh tempo'],['name','Nama'],['amount','Nominal'],['status','Status']]} money="amount" action={x=><div className="action-row"><button className="icon" onClick={async()=>{await supabase.from('obligations').update({status:x.status==='sudah'?'belum':'sudah'}).eq('id',x.id);refresh('Status kewajiban diperbarui.')}}>{x.status==='sudah'?'Buka':'Selesai'}</button><button className="icon" onClick={()=>archiveItem('obligations',x.id,x.name)}>Arsip</button></div>}/></section>}</>}

   {active==='Investasi'&&<><div className="tabs">{IT.map(x=><button key={x} className={it===x?'active':''} onClick={()=>setIt(x)}>{x}</button>)}</div>{it==='ETF'&&<AssetSection title="ETF Portfolio" add={()=>qa('etf')} tx={()=>qa('etfTx')}>{etfs.map(a=>{const m=etfM(a);return <article className="card pad" key={a.id}><div className="card-head"><div><span className="ticker">{a.ticker}</span><h3>{a.name}</h3><small className="muted">{a.broker}</small></div><button className="icon" onClick={()=>archiveItem('etf_assets',a.id,a.ticker)}>Arsip</button></div><div className="metric-row"><Metric t="Modal" v={rp(m.invested)}/><Metric t="Nilai" v={rp(m.value)}/><Metric t="P/L" v={rp(m.pl)} tone={m.pl>=0?'positive':'negative'}/><Metric t="Target" v={`${Number(a.target_allocation||0)}%`}/></div><InlineAsset fields={[['Harga sekarang','current_price',a.current_price],['Nilai portofolio','current_value',a.current_value],['Target alokasi %','target_allocation',a.target_allocation]]} onSave={p=>saveAsset('etf_assets',a.id,p)}/></article>})}</AssetSection>}{it==='Emas'&&<AssetSection title="Investasi Emas" add={()=>qa('gold')} tx={()=>qa('goldTx')}>{golds.map(a=>{const m=goldM(a);return <article className="card pad" key={a.id}><div className="card-head"><div><h3>{a.name}</h3><small className="muted">{a.platform}</small></div><button className="icon" onClick={()=>archiveItem('gold_assets',a.id,a.name)}>Arsip</button></div><div className="metric-row"><Metric t="Gram" v={`${num(m.grams)} g`}/><Metric t="Modal" v={rp(m.invested)}/><Metric t="Nilai" v={rp(m.value)}/><Metric t="P/L" v={rp(m.pl)} tone={m.pl>=0?'positive':'negative'}/></div><InlineAsset fields={[['Harga / gram','current_price_per_gram',a.current_price_per_gram],['Target alokasi %','target_allocation',a.target_allocation]]} onSave={p=>saveAsset('gold_assets',a.id,p)}/></article>})}</AssetSection>}{it==='Dividen'&&<AssetSection title="Saham Dividen" add={()=>qa('stock')} tx={()=>qa('stockTx')} extra={<button className="btn alt" onClick={()=>qa('dividend')}>＋ Dividen</button>}>{stocks.map(a=>{const m=stockM(a);return <article className="card pad" key={a.id}><div className="card-head"><div><span className="ticker">{a.ticker}</span><h3>{a.name}</h3><small className="muted">{a.broker}</small></div><button className="icon" onClick={()=>archiveItem('dividend_stocks',a.id,a.ticker)}>Arsip</button></div><div className="metric-row"><Metric t="Modal" v={rp(m.invested)}/><Metric t="Nilai" v={rp(m.value)}/><Metric t="Dividen" v={rp(m.div)}/><Metric t="Total P/L" v={rp(m.pl)} tone={m.pl>=0?'positive':'negative'}/></div><InlineAsset fields={[['Harga sekarang','current_price',a.current_price],['Target alokasi %','target_allocation',a.target_allocation]]} onSave={p=>saveAsset('dividend_stocks',a.id,p)}/></article>})}</AssetSection>}</>}

   {active==='Tabungan'&&<><div className="panel-line"><h2>Target Tabungan</h2><div className="action-row"><button className="btn" onClick={()=>qa('savingGoal')}>＋ Target</button><button className="btn alt" onClick={()=>qa('savingDeposit')}>Deposit</button></div></div><div className="cards">{savings.map(s=>{const v=saved(s.id),p=Number(s.target)?Math.min(100,v/Number(s.target)*100):0;return <article className="card pad" key={s.id}><div className="card-head"><div><h3>{s.name}</h3><small className="muted">{s.location}</small></div><button className="icon" onClick={()=>archiveItem('savings',s.id,s.name)}>Arsip</button></div><div className="big">{rp(v)}</div><p className="muted">Target {rp(s.target)} · Sisa {rp(Math.max(0,Number(s.target)-v))}</p><div className="progress"><div style={{width:`${p}%`}}/></div></article>})}</div></>}

   {active==='Hutang'&&<><div className="panel-line"><h2>Hutang</h2><div className="action-row"><button className="btn" onClick={()=>qa('debt')}>＋ Hutang</button><button className="btn alt" onClick={()=>qa('debtPayment')}>Bayar</button></div></div><div className="cards">{debts.map(d=>{const left=debtLeft(d),paid=Number(d.original_amount)-left,p=Number(d.original_amount)?paid/Number(d.original_amount)*100:0;return <article className="card pad" key={d.id}><div className="card-head"><div><h3>{d.name}</h3><small className="muted">{d.source}</small></div><button className="icon" onClick={()=>archiveItem('debts',d.id,d.name)}>Arsip</button></div><div className="big">{rp(left)}</div><p className="muted">Awal {rp(d.original_amount)} · Terbayar {rp(paid)}</p><div className="progress"><div style={{width:`${Math.min(100,p)}%`}}/></div></article>})}</div></>}

   {active==='Wishlist'&&<><div className="panel-line"><h2>Wishlist</h2><div className="action-row"><button className="btn" onClick={()=>qa('wishlist')}>＋ Wishlist</button><button className="btn alt" onClick={()=>qa('part')}>＋ Part</button></div></div><div className="cards">{wishes.map(w=>{const ps=parts.filter(x=>x.wishlist_id===w.id),partsTotal=sum(ps,'price'),partsBought=sum(ps.filter(x=>x.bought),'price'),saved=Number(w.saved||0)+partsBought,target=Number(w.target||0)||partsTotal,p=target?Math.min(100,saved/target*100):0;return <article className="card goal" key={w.id}>{w.image_url?<img className="goal-img" src={w.image_url} alt=""/>:<div className="goal-img placeholder">No image</div>}<div className="pad"><div className="card-head"><div><h3>{w.name}</h3><small className="muted">{w.brand}</small></div><button className="icon" onClick={()=>archiveItem('wishlists',w.id,w.name)}>Arsip</button></div><p>{rp(saved)} / {rp(target)}</p><div className="progress"><div style={{width:`${p}%`}}/></div><div className="parts">{ps.map(x=><div className="part" key={x.id}><label><input type="checkbox" checked={!!x.bought} onChange={async e=>{await supabase.from('wishlist_parts').update({bought:e.target.checked}).eq('id',x.id);refresh('Status part diperbarui.')}}/><span className={x.bought?'strike':''}>{x.name}<small>{x.brand}</small></span></label><b>{rp(x.price)}</b></div>)}</div>{w.link&&<a className="link" href={w.link} target="_blank" rel="noreferrer">Buka produk ↗</a>}</div></article>})}</div></>}

   {active==='Otomatis'&&<><div className="panel-line"><div><div className="kicker">Automation</div><h2>Transaksi Berulang</h2></div><div className="action-row"><button className="btn alt" onClick={runRecurring}>Jalankan jatuh tempo</button><button className="btn" onClick={()=>qa('recurring')}>＋ Jadwal</button></div></div><div className="cards">{recurring.map(x=><article className="card pad" key={x.id}><div className="card-head"><div><span className="badge pending">{x.kind}</span><h3>{x.name}</h3></div><button className="icon" onClick={async()=>{await supabase.from('recurring_transactions').update({active:!x.active}).eq('id',x.id);refresh('Jadwal diperbarui.')}}>{x.active?'Pause':'Aktifkan'}</button></div><div className="big">{rp(x.amount)}</div><p className="muted">{x.frequency} · berikutnya {x.next_run}</p></article>)}</div></>}

   {active==='Arsip'&&<section className="card pad"><div className="panel-line"><div><div className="kicker">Recycle Bin</div><h2>Arsip</h2></div><span className="muted">{archived.length} item</span></div>{archived.length===0?<p className="empty">Belum ada item diarsipkan.</p>:archived.map(x=><div className="archive-row" key={`${x._table}-${x.id}`}><div><b>{x._label}</b><small>{x._table} · {new Date(x.archived_at).toLocaleString('id-ID')}</small></div><button className="btn alt" onClick={()=>restoreItem(x)}>Pulihkan</button></div>)}</section>}
  </main>
  {quick&&<QuickAddModal kind={quick} open={!!quick} onClose={()=>setQuick(null)} hid={hid} uid={uid} period={{start:b.start,last:b.last}} assets={{etfs,golds,stocks,savings,debts,wishes}} onSaved={refresh}/>}<Toast message={toast} tone={toastTone} onDone={()=>setToast('')}/>
 </div>
}

function Metric({t,v,tone}:{t:string;v:string;tone?:string}){return <div className="metric"><span>{t}</span><b className={tone}>{v}</b></div>}
function Table({rows,columns,money,action}:{rows:R[];columns:[string,string][];money?:string;action?:(x:R)=>any}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c[0]}>{c[1]}</th>)}{action&&<th>Aksi</th>}</tr></thead><tbody>{rows.length===0?<tr><td colSpan={columns.length+(action?1:0)} className="empty">Belum ada data.</td></tr>:rows.map(x=><tr key={x.id}>{columns.map(c=><td key={c[0]}>{money===c[0]?rp(x[c[0]]):String(x[c[0]]??'—')}</td>)}{action&&<td>{action(x)}</td>}</tr>)}</tbody></table></div>}
function AssetSection({title,add,tx,extra,children}:{title:string;add:()=>void;tx:()=>void;extra?:any;children:any}){return <section><div className="panel-line"><h2>{title}</h2><div className="action-row"><button className="btn alt" onClick={tx}>＋ Transaksi</button>{extra}<button className="btn" onClick={add}>＋ Aset</button></div></div><div className="cards">{children}</div></section>}
function InlineAsset({fields,onSave}:{fields:[string,string,any][];onSave:(p:R)=>void}){const[v,setV]=useState<Record<string,string>>(Object.fromEntries(fields.map(x=>[x[1],String(x[2]??0)])));return <div className="inline-asset">{fields.map(f=><label key={f[1]}>{f[0]}<input type="number" value={v[f[1]]||''} onChange={e=>setV(x=>({...x,[f[1]]:e.target.value}))}/></label>)}<button className="btn alt" onClick={()=>onSave(Object.fromEntries(Object.entries(v).map(([k,val])=>[k,Number(val||0)])))}>Update</button></div>}
