'use client';
import {useState} from 'react';
import {AllocationChart} from './InvestmentCharts';

type R=Record<string,any>;
const rp=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const num=(n:number)=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:6}).format(Number(n||0));
export default function InvestmentView({it,setIt,etfs,etfTx,golds,goldTx,stocks,stockTx,divs,onQuick,onSave,onArchive,onDeleteTx}:{it:string;setIt:(v:string)=>void;etfs:R[];etfTx:R[];golds:R[];goldTx:R[];stocks:R[];stockTx:R[];divs:R[];onQuick:(k:any)=>void;onSave:(table:string,id:string,patch:R,message?:string)=>void;onArchive:(table:string,id:string,label:string)=>void;onDeleteTx:(table:string,id:string,label:string)=>void}){
 const sum=(rows:R[])=>rows.reduce((s,x)=>s+Number(x.amount||0),0);
 const etfM=(a:R)=>{const tx=etfTx.filter(x=>x.asset_id===a.id),buys=tx.filter(x=>x.type==='buy'),sells=tx.filter(x=>x.type==='sell'),invested=sum(buys),proceeds=sum(sells),net=Math.max(0,invested-proceeds),value=Number(a.current_value||0)>0?Number(a.current_value):net,pl=value+proceeds-invested,pct=invested?pl/invested*100:0;return{tx,invested,proceeds,value,pl,pct}};
 const goldM=(a:R)=>{const tx=goldTx.filter(x=>x.asset_id===a.id),buys=tx.filter(x=>x.type==='buy'),sells=tx.filter(x=>x.type==='sell'),grams=Math.max(0,buys.reduce((s,x)=>s+Number(x.grams||0),0)-sells.reduce((s,x)=>s+Number(x.grams||0),0)),invested=sum(buys),proceeds=sum(sells),value=grams*Number(a.current_price_per_gram||0),pl=value+proceeds-invested,pct=invested?pl/invested*100:0;return{tx,grams,invested,proceeds,value,pl,pct}};
 const stockM=(a:R)=>{const tx=stockTx.filter(x=>x.stock_id===a.id),buys=tx.filter(x=>x.type==='buy'),sells=tx.filter(x=>x.type==='sell'),units=Math.max(0,buys.reduce((s,x)=>s+Number(x.units||0),0)-sells.reduce((s,x)=>s+Number(x.units||0),0)),invested=sum(buys),proceeds=sum(sells),value=units*Number(a.current_price||0),ds=divs.filter(x=>x.stock_id===a.id),div=sum(ds),pl=value+proceeds+div-invested,pct=invested?pl/invested*100:0;return{tx,ds,units,invested,proceeds,value,div,pl,pct}};
 const etfItems=etfs.map(a=>({name:a.ticker||a.name||'ETF',value:etfM(a).value}));
 const goldItems=golds.map(a=>({name:a.name||a.platform||'Emas',value:goldM(a).value}));
 const stockItems=stocks.map(a=>({name:a.ticker||a.name||'Saham',value:stockM(a).value}));
 return <><div className="tabs">{['ETF','Emas','Dividen'].map(x=><button key={x} className={it===x?'active':''} onClick={()=>setIt(x)}>{x}</button>)}</div>
 {it==='ETF'&&<><AllocationChart compact kicker="Komposisi ETF" title="Persentase tiap ticker dari total ETF" items={etfItems}/><AssetSection title="ETF Portfolio" add={()=>onQuick('etf')} tx={()=>onQuick('etfTx')} txLabel="＋ Investasi / Jual">{etfs.map(a=>{const m=etfM(a);return <Card key={a.id} title={a.name} ticker={a.ticker} sub={`Broker: ${a.broker||'—'}`} onArchive={()=>onArchive('etf_assets',a.id,a.ticker)} metrics={[['Total investasi',rp(m.invested)],['Nilai sekarang',rp(m.value)],['Untung / rugi',`${rp(m.pl)} · ${m.pct.toFixed(2)}%`,m.pl>=0?'positive':'negative']]}><Updater label="Nilai portofolio sekarang" value={a.current_value||m.value} onSave={v=>onSave('etf_assets',a.id,{current_value:v},'Nilai portofolio ETF diperbarui.')}/><History rows={m.tx} mode="etf" onDelete={x=>onDeleteTx('etf_transactions',x.id,'transaksi ETF')}/></Card>})}</AssetSection></>}
 {it==='Emas'&&<><AllocationChart compact kicker="Komposisi Emas" title="Persentase tiap aset emas" items={goldItems}/><AssetSection title="Investasi Emas" add={()=>onQuick('gold')} tx={()=>onQuick('goldTx')} txLabel="＋ Beli / Jual">{golds.map(a=>{const m=goldM(a);return <Card key={a.id} title={a.name} sub={a.platform||'—'} onArchive={()=>onArchive('gold_assets',a.id,a.name)} metrics={[['Emas tersisa',`${num(m.grams)} g`],['Total investasi',rp(m.invested)],['Nilai sekarang',rp(m.value)],['Untung / rugi',`${rp(m.pl)} · ${m.pct.toFixed(2)}%`,m.pl>=0?'positive':'negative']]}><Updater label="Harga emas sekarang / gram" value={a.current_price_per_gram||0} onSave={v=>onSave('gold_assets',a.id,{current_price_per_gram:v},'Harga emas sekarang diperbarui.')}/><History rows={m.tx} mode="gold" onDelete={x=>onDeleteTx('gold_transactions',x.id,'transaksi emas')}/></Card>})}</AssetSection></>}
 {it==='Dividen'&&<><AllocationChart compact kicker="Komposisi Saham Dividen" title="Persentase tiap saham dari total saham dividen" items={stockItems}/><AssetSection title="Saham Dividen" add={()=>onQuick('stock')} tx={()=>onQuick('stockTx')} txLabel="＋ Beli / Jual" extra={<button className="btn alt" onClick={()=>onQuick('dividend')}>＋ Catat Dividen</button>}>{stocks.map(a=>{const m=stockM(a);return <Card key={a.id} title={a.name} ticker={a.ticker} sub={`Broker: ${a.broker||'—'}`} onArchive={()=>onArchive('dividend_stocks',a.id,a.ticker)} metrics={[['Unit tersisa',num(m.units)],['Total investasi',rp(m.invested)],['Nilai sekarang',rp(m.value)],['Dividen',rp(m.div)],['Total return',`${rp(m.pl)} · ${m.pct.toFixed(2)}%`,m.pl>=0?'positive':'negative']]}><Updater label="Harga saham sekarang / unit" value={a.current_price||0} onSave={v=>onSave('dividend_stocks',a.id,{current_price:v},'Harga saham sekarang diperbarui.')}/><History rows={m.tx} mode="stock" dividends={m.ds} onDelete={x=>onDeleteTx(x._kind==='Dividen'?'dividends':'dividend_stock_transactions',x.id,x._kind==='Dividen'?'dividen':'transaksi saham')}/></Card>})}</AssetSection></>}
 </>}
function AssetSection({title,add,tx,txLabel,extra,children}:{title:string;add:()=>void;tx:()=>void;txLabel:string;extra?:any;children:any}){return <section className="investment-assets-section"><div className="panel-line"><h2>{title}</h2><div className="action-row"><button className="btn alt" onClick={tx}>{txLabel}</button>{extra}<button className="btn" onClick={add}>＋ Aset</button></div></div><div className="cards">{children}</div></section>}
function Card({title,ticker,sub,onArchive,metrics,children}:{title:string;ticker?:string;sub?:string;onArchive:()=>void;metrics:[string,string,string?][];children:any}){return <article className="card pad"><div className="card-head"><div>{ticker&&<span className="ticker">{ticker}</span>}<h3>{title}</h3><small className="muted">{sub}</small></div><button className="icon" onClick={onArchive}>Arsip</button></div><div className="metric-row">{metrics.map(m=><div className="metric" key={m[0]}><span>{m[0]}</span><b className={m[2]}>{m[1]}</b></div>)}</div>{children}</article>}
function Updater({label,value,onSave}:{label:string;value:number;onSave:(v:number)=>void}){const[v,setV]=useState(String(value||0));return <div className="inline-asset"><label>{label}<input type="number" value={v} onChange={e=>setV(e.target.value)}/></label><button className="btn alt" onClick={()=>onSave(Number(v||0))}>Update</button></div>}
function History({rows,mode,dividends=[],onDelete}:{rows:R[];mode:'etf'|'gold'|'stock';dividends?:R[];onDelete:(x:R)=>void}){const all=[...rows.map(x=>({...x,_kind:x.type==='sell'?'Jual':'Beli'})),...dividends.map(x=>({...x,_kind:'Dividen'}))].sort((a,b)=>String(b.happened_at).localeCompare(String(a.happened_at)));return <details className="inv-history"><summary>Riwayat transaksi ({all.length})</summary>{all.length===0?<p className="empty">Belum ada transaksi.</p>:<div className="history-list">{all.map(x=><div key={x.id} className="history-row"><div><b>{x._kind}</b><small>{x.happened_at}</small></div><div className="history-amount"><b>{rp(x.amount)}</b>{mode==='gold'&&x._kind!=='Dividen'&&<small>{num(x.grams)} g · {rp(x.price_per_gram)}/g</small>}{mode==='stock'&&x._kind!=='Dividen'&&<small>{num(x.units)} unit</small>}</div><button className="icon danger" onClick={()=>onDelete(x)}>Hapus</button></div>)}</div>}</details>}
