'use client';
import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {supabase} from '@/lib/supabase';
import InvestmentView from './InvestmentView';
import {AllocationChart} from './InvestmentCharts';
import QuickAddModal,{QuickAddKind} from './QuickAddModal';
import {Toast} from '@/app/components/UiKit';

type R=Record<string,any>;
const sum=(a:R[])=>a.reduce((s,x)=>s+Number(x.amount||0),0);
export default function InvestmentExperience({houses}:{houses:R[]}){
 const[uid,setUid]=useState(''),[hid,setHid]=useState(''),[open,setOpen]=useState(false),[it,setIt]=useState('ETF'),[quick,setQuick]=useState<QuickAddKind|null>(null),[toast,setToast]=useState('');
 const[etfs,setEtfs]=useState<R[]>([]),[etfTx,setEtfTx]=useState<R[]>([]),[golds,setGolds]=useState<R[]>([]),[goldTx,setGoldTx]=useState<R[]>([]),[stocks,setStocks]=useState<R[]>([]),[stockTx,setStockTx]=useState<R[]>([]),[divs,setDivs]=useState<R[]>([]),[portal,setPortal]=useState<HTMLElement|null>(null),[dashboardActive,setDashboardActive]=useState(true);
 async function child(t:string,c:string,ids:string[]){if(!ids.length)return[];const r=await supabase.from(t).select('*').in(c,ids).order('created_at',{ascending:false});return r.data||[]}
 async function load(id:string){if(!id)return;const[a,b,c]=await Promise.all([supabase.from('etf_assets').select('*').eq('household_id',id).is('archived_at',null).order('created_at'),supabase.from('gold_assets').select('*').eq('household_id',id).is('archived_at',null).order('created_at'),supabase.from('dividend_stocks').select('*').eq('household_id',id).is('archived_at',null).order('created_at')]);const ea=a.data||[],ga=b.data||[],sa=c.data||[];setEtfs(ea);setGolds(ga);setStocks(sa);const[et,gt,st,dv]=await Promise.all([child('etf_transactions','asset_id',ea.map(x=>x.id)),child('gold_transactions','asset_id',ga.map(x=>x.id)),child('dividend_stock_transactions','stock_id',sa.map(x=>x.id)),child('dividends','stock_id',sa.map(x=>x.id))]);setEtfTx(et);setGoldTx(gt);setStockTx(st);setDivs(dv)}
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUid(data.user?.id||''));if(houses[0]){setHid(houses[0].id);load(houses[0].id)}},[houses]);
 useEffect(()=>{const click=(e:MouseEvent)=>{const btn=(e.target as HTMLElement)?.closest('button');if(!btn)return;const txt=(btn.textContent||'').trim();if(txt==='Investasi'&&btn.closest('.refined-sidebar')){e.preventDefault();e.stopPropagation();setOpen(true);return}setTimeout(()=>{const active=document.querySelector('.refined-sidebar .nav-active');setDashboardActive((active?.textContent||'').trim()==='Dashboard')},0)};const change=(e:Event)=>{const el=e.target as HTMLSelectElement;if(el?.closest('.fv-actions')&&el.tagName==='SELECT'&&el.value){setHid(el.value);load(el.value)}};document.addEventListener('click',click,true);document.addEventListener('change',change,true);return()=>{document.removeEventListener('click',click,true);document.removeEventListener('change',change,true)}},[]);
 useEffect(()=>{if(!dashboardActive){setPortal(null);document.getElementById('investment-chart-portal')?.remove();document.querySelector('.asset-list')?.classList.remove('investment-list-replaced');return}const list=document.querySelector('.asset-list') as HTMLElement|null;if(!list)return;list.classList.add('investment-list-replaced');let node=document.getElementById('investment-chart-portal');if(!node){node=document.createElement('div');node.id='investment-chart-portal';list.insertAdjacentElement('afterend',node)}setPortal(node);return()=>{list.classList.remove('investment-list-replaced');node?.remove()}},[dashboardActive]);
 const etfValue=(a:R)=>{const tx=etfTx.filter(x=>x.asset_id===a.id),buy=sum(tx.filter(x=>x.type==='buy')),sell=sum(tx.filter(x=>x.type==='sell')),net=Math.max(0,buy-sell);return Number(a.current_value||0)>0?Number(a.current_value):net};
 const goldValue=(a:R)=>{const tx=goldTx.filter(x=>x.asset_id===a.id),buys=tx.filter(x=>x.type==='buy'),sells=tx.filter(x=>x.type==='sell'),grams=Math.max(0,buys.reduce((s,x)=>s+Number(x.grams||0),0)-sells.reduce((s,x)=>s+Number(x.grams||0),0));return grams*Number(a.current_price_per_gram||0)};
 const stockValue=(a:R)=>{const tx=stockTx.filter(x=>x.stock_id===a.id),buys=tx.filter(x=>x.type==='buy'),sells=tx.filter(x=>x.type==='sell'),units=Math.max(0,buys.reduce((s,x)=>s+Number(x.units||0),0)-sells.reduce((s,x)=>s+Number(x.units||0),0));return units*Number(a.current_price||0)};
 const totals=useMemo(()=>({etf:etfs.reduce((s,a)=>s+etfValue(a),0),gold:golds.reduce((s,a)=>s+goldValue(a),0),stock:stocks.reduce((s,a)=>s+stockValue(a),0)}),[etfs,etfTx,golds,goldTx,stocks,stockTx]);
 async function refresh(message?:string){await load(hid);if(message)setToast(message)}
 async function save(table:string,id:string,patch:R,message?:string){const r=await supabase.from(table).update(patch).eq('id',id);if(r.error)setToast(r.error.message);else refresh(message||'Data investasi diperbarui.')}
 async function archive(table:string,id:string,label:string){if(!confirm(`Arsipkan ${label}?`))return;const r=await supabase.from(table).update({archived_at:new Date().toISOString()}).eq('id',id);if(r.error)setToast(r.error.message);else refresh(`${label} dipindahkan ke Arsip.`)}
 const dashboardChart=<AllocationChart compact kicker="Komposisi Investasi" title="ETF vs Emas vs Saham Dividen" items={[{name:'ETF',value:totals.etf},{name:'Emas',value:totals.gold},{name:'Saham Dividen',value:totals.stock}]}/>;
 return <>{portal&&dashboardActive&&createPortal(dashboardChart,portal)}{open&&<div className="investment-overlay"><div className="investment-overlay-panel"><header className="investment-overlay-head"><div><div className="kicker">Investment Center</div><h1>Portofolio Investasi</h1><p className="muted">Catat investasi, update nilai sekarang, jual aset, dan lihat untung/rugi.</p></div><div className="action-row"><select value={hid} onChange={e=>{setHid(e.target.value);load(e.target.value)}}>{houses.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select><button className="btn alt" onClick={()=>setOpen(false)}>Tutup</button></div></header><InvestmentView it={it} setIt={setIt} etfs={etfs} etfTx={etfTx} golds={golds} goldTx={goldTx} stocks={stocks} stockTx={stockTx} divs={divs} onQuick={(k:any)=>setQuick(k)} onSave={save} onArchive={archive}/></div></div>}{quick&&<QuickAddModal kind={quick} open={!!quick} onClose={()=>setQuick(null)} hid={hid} uid={uid} period={{start:today(),last:today()}} assets={{etfs,golds,stocks,savings:[],debts:[],wishes:[]}} onSaved={refresh}/>}<Toast message={toast} tone="success" onDone={()=>setToast('')}/></>}
function today(){return new Date().toISOString().slice(0,10)}
