'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {supabase} from '@/lib/supabase';

type R=Record<string,any>;
const NAV=['Dashboard','Finance','Investasi','Tabungan','Hutang','Wishlist'];
const FT=['Income','Expenses','Budgeting','Kewajiban'];
const IT=['ETF','Emas','Dividen'];
const palette=['#111827','#3567a8','#9c6a16','#1f7a50','#73539d','#b64545','#577590'];
const rp=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const num=(n:number)=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:6}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const sum=(a:R[])=>a.reduce((s,x)=>s+Number(x.amount||0),0);
function pkey(s:string){const d=new Date(s+'T00:00:00');let y=d.getFullYear(),m=d.getMonth();if(d.getDate()<22){m--;if(m<0){m=11;y--}}return `${y}-${String(m+1).padStart(2,'0')}`}
function pb(k:string){const [y,m]=k.split('-').map(Number),a=new Date(y,m-1,22),e=new Date(y,m,22),l=new Date(e);l.setDate(l.getDate()-1);const z=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return{start:z(a),end:z(e),last:z(l)}}
function plabel(k:string){const b=pb(k),f=new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric'});return `${f.format(new Date(b.start+'T00:00:00'))} – ${f.format(new Date(b.last+'T00:00:00'))}`}
function ask(t:string,v=''){const x=window.prompt(t,v);return x===null?null:x.trim()}
function askN(t:string,v='0'){const x=ask(t,v);if(x===null)return null;const n=Number(x);return Number.isFinite(n)?n:null}

function Donut({items,label}:{items:{name:string,value:number}[],label:string}){
 const rows=items.filter(x=>x.value>0),total=rows.reduce((s,x)=>s+x.value,0);let at=0;const parts=rows.map((x,i)=>{const p=total?x.value/total*100:0;const s=`${palette[i%palette.length]} ${at}% ${at+p}%`;at+=p;return s});
 if(!total)return <div className="empty">Belum ada data.</div>;
 return <div style={{display:'grid',gridTemplateColumns:'190px 1fr',gap:22,alignItems:'center'}}><div style={{position:'relative',width:180,height:180,margin:'auto'}}><div style={{width:180,height:180,borderRadius:'50%',background:`conic-gradient(${parts.join(',')})`}}/><div style={{position:'absolute',inset:37,borderRadius:'50%',background:'#fff',display:'grid',placeItems:'center',textAlign:'center',boxShadow:'inset 0 0 0 1px #eef0f2'}}><div><b style={{fontSize:18}}>{rp(total)}</b><div className="muted" style={{fontSize:11}}>{label}</div></div></div></div><div>{rows.map((x,i)=><div key={x.name} style={{display:'grid',gridTemplateColumns:'12px 1fr auto',gap:9,alignItems:'center',margin:'10px 0'}}><span style={{width:11,height:11,borderRadius:'50%',background:palette[i%palette.length]}}/><b>{x.name}</b><span>{Math.round(x.value/total*100)}% • {rp(x.value)}</span></div>)}</div></div>
}

export default function Page(){
 const router=useRouter();
 const [uid,setUid]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(true),[err,setErr]=useState('');
 const [houses,setHouses]=useState<R[]>([]),[hid,setHid]=useState(''),[houseName,setHouseName]=useState('Keluarga Kita');
 const [active,setActive]=useState('Dashboard'),[ft,setFt]=useState('Income'),[it,setIt]=useState('ETF'),[period,setPeriod]=useState(pkey(today()));
 const [income,setIncome]=useState<R[]>([]),[expenses,setExpenses]=useState<R[]>([]),[budgets,setBudgets]=useState<R[]>([]),[obligations,setObligations]=useState<R[]>([]);
 const [etfs,setEtfs]=useState<R[]>([]),[etfTx,setEtfTx]=useState<R[]>([]),[golds,setGolds]=useState<R[]>([]),[goldTx,setGoldTx]=useState<R[]>([]),[stocks,setStocks]=useState<R[]>([]),[stockTx,setStockTx]=useState<R[]>([]),[divs,setDivs]=useState<R[]>([]);
 const [savings,setSavings]=useState<R[]>([]),[savingTx,setSavingTx]=useState<R[]>([]),[debts,setDebts]=useState<R[]>([]),[debtPay,setDebtPay]=useState<R[]>([]),[wishes,setWishes]=useState<R[]>([]),[parts,setParts]=useState<R[]>([]);
 const b=pb(period),inside=(d:string)=>!!d&&d>=b.start&&d<b.end;
 async function top(table:string,id:string){const r=await supabase.from(table).select('*').eq('household_id',id).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
 async function child(table:string,col:string,ids:string[]){if(!ids.length)return[];const r=await supabase.from(table).select('*').in(col,ids).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
 async function loadHouse(){const r=await supabase.from('households').select('id,name').order('created_at');if(r.error)throw r.error;setHouses(r.data||[]);return r.data||[]}
 async function load(id:string){setBusy(true);setErr('');try{const [a,c,d,e,f,g,h,i,j,k]=await Promise.all([top('income',id),top('expenses',id),top('budgets',id),top('obligations',id),top('etf_assets',id),top('gold_assets',id),top('dividend_stocks',id),top('savings',id),top('debts',id),top('wishlists',id)]);setIncome(a);setExpenses(c);setBudgets(d);setObligations(e);setEtfs(f);setGolds(g);setStocks(h);setSavings(i);setDebts(j);setWishes(k);const [l,m,n,o,p,q,r]=await Promise.all([child('etf_transactions','asset_id',f.map(x=>x.id)),child('gold_transactions','asset_id',g.map(x=>x.id)),child('dividend_stock_transactions','stock_id',h.map(x=>x.id)),child('dividends','stock_id',h.map(x=>x.id)),child('saving_transactions','saving_id',i.map(x=>x.id)),child('debt_payments','debt_id',j.map(x=>x.id)),child('wishlist_parts','wishlist_id',k.map(x=>x.id))]);setEtfTx(l);setGoldTx(m);setStockTx(n);setDivs(o);setSavingTx(p);setDebtPay(q);setParts(r)}catch(e:any){setErr(e.message||'Gagal memuat data')}finally{setBusy(false)}}
 useEffect(()=>{(async()=>{const {data,error}=await supabase.auth.getUser();if(error||!data.user){router.replace('/login');return}setUid(data.user.id);setEmail(data.user.email||'');try{const h=await loadHouse();if(h[0]){setHid(h[0].id);await load(h[0].id)}}catch(e:any){setErr(e.message||'Gagal memuat data')}finally{setBusy(false)}})()},[router]);
 async function createHouse(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await supabase.from('households').insert({name:houseName.trim(),created_by:uid}).select('id,name').single();if(r.error)throw r.error;setHouses([r.data]);setHid(r.data.id);await load(r.data.id)}catch(e:any){setErr(e.message||'Gagal membuat household')}finally{setBusy(false)}}
 async function go(fn:()=>any){setErr('');try{const r=await fn();if(r?.error)throw r.error;await load(hid)}catch(e:any){setErr(e.message||'Gagal menyimpan')}}
 async function del(t:string,id:string,label:string){if(confirm(`Hapus ${label} ini?`))await go(()=>supabase.from(t).delete().eq('id',id))}
 async function logout(){await supabase.auth.signOut();router.replace('/login')}
 const pi=income.filter(x=>inside(x.happened_at)),pe=expenses.filter(x=>inside(x.happened_at)),pbud=budgets.filter(x=>x.period_start===b.start),pob=obligations.filter(x=>inside(x.due_date));
 const etfM=(a:R)=>{const tx=etfTx.filter(x=>x.asset_id===a.id),buy=sum(tx.filter(x=>x.type==='buy')),sell=sum(tx.filter(x=>x.type==='sell')),invested=Math.max(0,buy-sell),value=Number(a.current_value||0)||invested;return{tx,invested,value,pl:value-invested}};
 const goldM=(a:R)=>{const tx=goldTx.filter(x=>x.asset_id===a.id),buy=tx.filter(x=>x.type==='buy'),sell=tx.filter(x=>x.type==='sell'),grams=Math.max(0,buy.reduce((s,x)=>s+Number(x.grams||0),0)-sell.reduce((s,x)=>s+Number(x.grams||0),0)),invested=sum(buy),proceeds=sum(sell),value=grams*Number(a.current_price_per_gram||0);return{tx,grams,invested,value,pl:value+proceeds-invested}};
 const stockM=(a:R)=>{const tx=stockTx.filter(x=>x.stock_id===a.id),buy=tx.filter(x=>x.type==='buy'),sell=tx.filter(x=>x.type==='sell'),units=Math.max(0,buy.reduce((s,x)=>s+Number(x.units||0),0)-sell.reduce((s,x)=>s+Number(x.units||0),0)),invested=sum(buy),proceeds=sum(sell),value=units*Number(a.current_price||0),div=sum(divs.filter(x=>x.stock_id===a.id));return{tx,units,invested,value,div,total:value+proceeds+div-invested}};
 const sav=(id:string)=>sum(savingTx.filter(x=>x.saving_id===id));const debtLeft=(d:R)=>Math.max(0,Number(d.original_amount||0)-sum(debtPay.filter(x=>x.debt_id===d.id)));
 const ti=sum(pi),te=sum(pe),left=ti-te,rem=pob.filter(x=>x.status!=='sudah').reduce((s,x)=>s+Number(x.amount||0),0),totalDebt=debts.reduce((s,d)=>s+debtLeft(d),0),totalETF=etfs.reduce((s,a)=>s+etfM(a).value,0),totalGold=golds.reduce((s,a)=>s+goldM(a).value,0),totalStock=stocks.reduce((s,a)=>s+stockM(a).value,0),totalSav=savings.reduce((s,a)=>s+sav(a.id),0);
 const goldInvested=golds.reduce((s,a)=>s+goldM(a).invested,0),goldGrams=golds.reduce((s,a)=>s+goldM(a).grams,0),goldPL=totalGold-goldInvested;
 const stockInvested=stocks.reduce((s,a)=>s+stockM(a).invested,0),stockDiv=stocks.reduce((s,a)=>s+stockM(a).div,0),stockYield=stockInvested?stockDiv/stockInvested*100:0;
 async function addIncome(){const source=ask('Sumber income');if(!source)return;const amount=askN('Nominal');if(amount===null)return;const date=ask('Tanggal (YYYY-MM-DD)',today());if(!date)return;await go(()=>supabase.from('income').insert({household_id:hid,source,amount,happened_at:date,created_by:uid}))}
 async function addExpense(){const name=ask('Keperluan');if(!name)return;const amount=askN('Nominal');if(amount===null)return;const category=ask('Kategori','Lainnya')||'Lainnya';const date=ask('Tanggal (YYYY-MM-DD)',today());if(!date)return;await go(()=>supabase.from('expenses').insert({household_id:hid,name,category,amount,happened_at:date,created_by:uid}))}
 async function addBudget(){const category=ask('Kategori budget');if(!category)return;const amount=askN('Batas budget');if(amount===null)return;await go(()=>supabase.from('budgets').insert({household_id:hid,category,amount,manual_used:null,period_start:b.start,period_end:b.last}))}
 async function addOb(){const name=ask('Nama kewajiban');if(!name)return;const amount=askN('Nominal');if(amount===null)return;await go(()=>supabase.from('obligations').insert({household_id:hid,name,amount,status:'belum',due_date:b.start}))}
 async function toggleOb(o:R){await go(()=>supabase.from('obligations').update({status:o.status==='sudah'?'belum':'sudah'}).eq('id',o.id))}
 async function addETF(){const ticker=ask('Ticker ETF');if(!ticker)return;const name=ask('Nama ETF')||ticker;const broker=ask('Broker','XTB')||'';await go(()=>supabase.from('etf_assets').insert({household_id:hid,ticker,name,broker,current_price:0,current_value:0}))}
 async function etfAction(a:R,type:'buy'|'sell'){const amount=askN(type==='sell'?'Hasil penjualan / dana keluar':'Nominal top up');if(amount===null)return;const date=ask('Tanggal',today());if(!date)return;await go(()=>supabase.from('etf_transactions').insert({asset_id:a.id,type,amount,happened_at:date}))}
 async function updateETF(a:R){const price=askN('Harga ETF sekarang',String(a.current_price||0));if(price===null)return;const value=askN('Nilai portofolio sekarang',String(a.current_value||0));if(value===null)return;await go(()=>supabase.from('etf_assets').update({current_price:price,current_value:value}).eq('id',a.id))}
 async function addGold(){const name=ask('Nama akun emas','Emas Digital');if(!name)return;const platform=ask('Platform','Pluang')||'';const price=askN('Harga emas / gram','0');if(price===null)return;await go(()=>supabase.from('gold_assets').insert({household_id:hid,name,platform,current_price_per_gram:price}))}
 async function goldAction(a:R,type:'buy'|'sell'){const amount=askN(type==='sell'?'Hasil penjualan':'Nominal investasi');if(amount===null)return;const grams=askN('Jumlah gram');if(grams===null)return;const price=askN('Harga / gram');if(price===null)return;const date=ask('Tanggal',today());if(!date)return;await go(()=>supabase.from('gold_transactions').insert({asset_id:a.id,type,amount,grams,price_per_gram:price,happened_at:date}))}
 async function updateGold(a:R){const price=askN('Harga emas sekarang / gram',String(a.current_price_per_gram||0));if(price===null)return;await go(()=>supabase.from('gold_assets').update({current_price_per_gram:price}).eq('id',a.id))}
 async function addStock(){const ticker=ask('Ticker saham');if(!ticker)return;const name=ask('Nama saham')||ticker;const broker=ask('Broker','Pluang')||'';const price=askN('Harga saham sekarang / lembar','0');if(price===null)return;await go(()=>supabase.from('dividend_stocks').insert({household_id:hid,ticker,name,broker,current_price:price}))}
 async function stockAction(a:R,type:'buy'|'sell'){const amount=askN(type==='sell'?'Hasil penjualan':'Nominal investasi');if(amount===null)return;const units=askN('Jumlah lembar');if(units===null)return;const date=ask('Tanggal',today());if(!date)return;await go(()=>supabase.from('dividend_stock_transactions').insert({stock_id:a.id,type,amount,units,happened_at:date}))}
 async function updateStockPrice(a:R){const price=askN('Harga saham sekarang / lembar',String(a.current_price||0));if(price===null)return;await go(()=>supabase.from('dividend_stocks').update({current_price:price}).eq('id',a.id))}
 async function addDiv(a:R){const amount=askN('Nominal dividen');if(amount===null)return;const date=ask('Tanggal dibagikan',today());if(!date)return;await go(()=>supabase.from('dividends').insert({stock_id:a.id,amount,happened_at:date}))}
 async function addSaving(){const name=ask('Nama tabungan');if(!name)return;const location=ask('Disimpan di mana?','Bank Jago')||'';const target=askN('Target','0');if(target===null)return;await go(()=>supabase.from('savings').insert({household_id:hid,name,location,target}))}
 async function deposit(s:R){const amount=askN('Nominal deposit');if(amount===null)return;const date=ask('Tanggal',today());if(!date)return;await go(()=>supabase.from('saving_transactions').insert({saving_id:s.id,amount,happened_at:date}))}
 async function addDebt(){const name=ask('Keperluan hutang');if(!name)return;const source=ask('Sumber / kreditur','')||'';const amount=askN('Total hutang');if(amount===null)return;const date=ask('Tanggal hutang',today());if(!date)return;await go(()=>supabase.from('debts').insert({household_id:hid,name,source,original_amount:amount,borrow_date:date}))}
 async function payDebt(d:R){const amount=askN('Nominal bayar');if(amount===null)return;const date=ask('Tanggal',today());if(!date)return;await go(()=>supabase.from('debt_payments').insert({debt_id:d.id,amount,happened_at:date}))}
 async function addWish(){const name=ask('Nama wishlist');if(!name)return;const brand=ask('Brand','')||'';const target=askN('Target harga','0');if(target===null)return;const link=ask('Link barang','')||'';const image=ask('URL gambar','')||'';await go(()=>supabase.from('wishlists').insert({household_id:hid,name,brand,target,saved:0,link,image_url:image,status:'active'}))}
 async function saveWish(w:R){const amount=askN('Tambah dana wishlist');if(amount===null)return;await go(()=>supabase.from('wishlists').update({saved:Number(w.saved||0)+amount}).eq('id',w.id))}
 async function addPart(w:R){const name=ask('Nama part / sub-item');if(!name)return;const brand=ask('Brand / model','')||'';const price=askN('Harga target','0');if(price===null)return;const link=ask('Link','')||'';await go(()=>supabase.from('wishlist_parts').insert({wishlist_id:w.id,name,brand,price,link,bought:false}))}
 async function togglePart(p:R){await go(()=>supabase.from('wishlist_parts').update({bought:!p.bought}).eq('id',p.id))}
 if(busy&&!uid)return <main className="center"><section className="auth-card"><div className="logo">Family Vault</div><p>Memuat…</p></section></main>;
 if(!houses.length)return <main className="center"><section className="auth-card"><div className="logo">Family Vault</div><h1>Buat Household</h1>{err&&<p className="status error">{err}</p>}<form onSubmit={createHouse}><label>Nama Household<input value={houseName} onChange={e=>setHouseName(e.target.value)} required/></label><button className="primary">Buat Household</button></form></section></main>;
 const tabs=<div className="tabs">{(active==='Finance'?FT:IT).map(x=><button key={x} className={(active==='Finance'?ft:it)===x?'active':''} onClick={()=>active==='Finance'?setFt(x):setIt(x)}>{x}</button>)}</div>;
 return <main className="shell"><aside className="sidebar"><div className="logo">Family Vault</div><p className="side-muted">Household Finance • Online v12</p><nav>{NAV.map(x=><button key={x} className={active===x?'nav-active':''} onClick={()=>setActive(x)}>{x}</button>)}</nav><div className="side-bottom"><small>{email}</small><button onClick={logout}>Keluar</button></div></aside><section className="content"><div className="topbar"><div><h1>{active}</h1><p className="muted">{active==='Dashboard'||active==='Finance'?`Periode ${plabel(period)}`:'Data household bersama'}</p></div>{(active==='Dashboard'||active==='Finance')&&<input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/>}</div>{err&&<p className="status error">{err}</p>}
 {active==='Dashboard'&&<><div className="stats five"><article className="card"><span>Income</span><strong>{rp(ti)}</strong></article><article className="card"><span>Expenses</span><strong>{rp(te)}</strong></article><article className="card"><span>Leftover</span><strong>{rp(left)}</strong></article><article className="card"><span>Sisa Kewajiban</span><strong>{rp(rem)}</strong></article><article className="card"><span>DBT / Hutang</span><strong>{rp(totalDebt)}</strong></article></div><div className="grid2"><article className="card pad"><div className="kicker">Assets</div><h2>Ringkasan Aset</h2><div className="assetSummary"><div><span>ETF</span><b>{rp(totalETF)}</b></div><div><span>Emas</span><b>{rp(totalGold)}</b></div><div><span>Saham Dividen</span><b>{rp(totalStock)}</b></div><div><span>Tabungan</span><b>{rp(totalSav)}</b></div></div><div className="total-box"><span>Total Aset</span><strong>{rp(totalETF+totalGold+totalStock+totalSav)}</strong></div></article><article className="card pad"><div className="kicker">ETF Portfolio</div><h2>Komposisi Dana ETF</h2><Donut label="Dana ETF" items={etfs.map(a=>({name:a.ticker,value:etfM(a).invested}))}/></article></div><div className="grid2"><article className="card pad"><div className="kicker">Gold Investment</div><h2>Ringkasan Investasi Emas</h2><div className="metric-row"><div className="metric"><span>Total Emas</span><b>{num(goldGrams)} gram</b></div><div className="metric"><span>Modal Emas</span><b>{rp(goldInvested)}</b></div><div className="metric"><span>Nilai Sekarang</span><b>{rp(totalGold)}</b></div><div className="metric"><span>Untung / Rugi</span><b className={goldPL>=0?'positive':'negative'}>{rp(goldPL)} {goldInvested?`(${(goldPL/goldInvested*100).toFixed(2)}%)`:''}</b></div></div></article><article className="card pad"><div className="kicker">Dividend Portfolio</div><h2>Saham Dividen</h2><Donut label="Modal Saham" items={stocks.map(a=>({name:a.ticker,value:stockM(a).invested}))}/><div className="metric-row"><div className="metric"><span>Total Dividen Diterima</span><b className="positive">{rp(stockDiv)}</b></div><div className="metric"><span>Dividend Return vs Modal</span><b>{stockYield.toFixed(2)}%</b></div><div className="metric"><span>Total Modal Dividen</span><b>{rp(stockInvested)}</b></div></div></article></div></>}
 {active==='Finance'&&<><div className="card pad period-card"><div className="kicker">Periode Aktif</div><b>{plabel(period)}</b></div>{tabs}{ft==='Income'&&<section className="card pad"><div className="card-head"><h2>Pemasukan</h2><button className="btn" onClick={addIncome}>+ Income</button></div><table><tbody>{pi.map(x=><tr key={x.id}><td>{x.happened_at}</td><td>{x.source}</td><td className="right positive">{rp(x.amount)}</td><td><button className="icon" onClick={()=>del('income',x.id,'income')}>Hapus</button></td></tr>)}</tbody></table></section>}{ft==='Expenses'&&<section className="card pad"><div className="card-head"><h2>Pengeluaran</h2><button className="btn" onClick={addExpense}>+ Expense</button></div><table><tbody>{pe.map(x=><tr key={x.id}><td>{x.happened_at}</td><td>{x.name}</td><td>{x.category}</td><td className="right negative">{rp(x.amount)}</td><td><button className="icon" onClick={()=>del('expenses',x.id,'expense')}>Hapus</button></td></tr>)}</tbody></table></section>}{ft==='Budgeting'&&<section><div className="card-head"><h2>Budget Bulanan</h2><button className="btn" onClick={addBudget}>+ Budget</button></div><div className="budgetGrid">{pbud.map(x=>{const used=Number(x.manual_used??pe.filter(e=>(e.category||'').toLowerCase()===(x.category||'').toLowerCase()).reduce((s,e)=>s+Number(e.amount||0),0));return <article className="card pad" key={x.id}><h3>{x.category}</h3><div className="metric-row"><div className="metric"><span>Budget</span><b>{rp(x.amount)}</b></div><div className="metric"><span>Terpakai</span><b>{rp(used)}</b></div><div className="metric"><span>Sisa</span><b>{rp(Number(x.amount)-used)}</b></div></div><button className="icon" onClick={()=>del('budgets',x.id,'budget')}>Hapus</button></article>})}</div></section>}{ft==='Kewajiban'&&<section className="card pad"><div className="card-head"><h2>Kewajiban Bulanan</h2><button className="btn" onClick={addOb}>+ Kewajiban</button></div><table><tbody>{pob.map(o=><tr key={o.id}><td><b>{o.name}</b></td><td>{rp(o.amount)}</td><td><button className={`badge ${o.status==='sudah'?'done':'pending'}`} onClick={()=>toggleOb(o)}>{o.status==='sudah'?'Sudah':'Belum'}</button></td><td><button className="icon" onClick={()=>del('obligations',o.id,'kewajiban')}>Hapus</button></td></tr>)}</tbody></table></section>}</>}
 {active==='Investasi'&&<>{tabs}{it==='ETF'&&<><button className="btn" onClick={addETF}>+ ETF Baru</button><div className="cards">{etfs.map(a=>{const m=etfM(a);return <article className="card pad" key={a.id}><div className="card-head"><div><span className="ticker">{a.ticker}</span><h3>{a.name}</h3><p className="muted">{a.broker}</p></div><button className="icon" onClick={()=>del('etf_assets',a.id,'ETF')}>Hapus</button></div><div className="metric-row"><div className="metric"><span>Modal</span><b>{rp(m.invested)}</b></div><div className="metric"><span>Nilai Sekarang</span><b>{rp(m.value)}</b></div><div className="metric"><span>P/L</span><b>{rp(m.pl)}</b></div></div><div className="goalActions"><button className="btn" onClick={()=>etfAction(a,'buy')}>+ Dana</button><button className="btn alt" onClick={()=>updateETF(a)}>Update Harga/Nilai</button><button className="btn alt" onClick={()=>etfAction(a,'sell')}>Jual/Tarik</button></div></article>})}</div></>}{it==='Emas'&&<><button className="btn" onClick={addGold}>+ Akun Emas</button><div className="cards">{golds.map(a=>{const m=goldM(a);return <article className="card pad" key={a.id}><div className="card-head"><div><span className="ticker">GOLD</span><h3>{a.name}</h3><p className="muted">{a.platform}</p></div><button className="icon" onClick={()=>del('gold_assets',a.id,'emas')}>Hapus</button></div><div className="metric-row"><div className="metric"><span>Gram</span><b>{num(m.grams)}</b></div><div className="metric"><span>Modal</span><b>{rp(m.invested)}</b></div><div className="metric"><span>Nilai</span><b>{rp(m.value)}</b></div></div><div className="goalActions"><button className="btn" onClick={()=>goldAction(a,'buy')}>+ Beli</button><button className="btn alt" onClick={()=>updateGold(a)}>Update Harga</button><button className="btn alt" onClick={()=>goldAction(a,'sell')}>Jual</button></div></article>})}</div></>}{it==='Dividen'&&<><button className="btn" onClick={addStock}>+ Saham Dividen</button><div className="cards">{stocks.map(a=>{const m=stockM(a);return <article className="card pad" key={a.id}><div className="card-head"><div><span className="ticker">{a.ticker}</span><h3>{a.name}</h3><p className="muted">{a.broker}</p></div><button className="icon" onClick={()=>del('dividend_stocks',a.id,'saham')}>Hapus</button></div><div className="metric-row"><div className="metric"><span>Harga Sekarang</span><b>{rp(a.current_price)}</b></div><div className="metric"><span>Nilai Sekarang</span><b>{rp(m.value)}</b></div><div className="metric"><span>Total Dividen</span><b>{rp(m.div)}</b></div></div><div className="goalActions"><button className="btn" onClick={()=>stockAction(a,'buy')}>+ Pembelian</button><button className="btn alt" onClick={()=>updateStockPrice(a)}>Update Harga Saham</button><button className="btn alt" onClick={()=>addDiv(a)}>+ Dividen</button><button className="btn alt" onClick={()=>stockAction(a,'sell')}>Jual Saham</button></div></article>})}</div></>}</>}
 {active==='Tabungan'&&<><button className="btn" onClick={addSaving}>+ Tabungan Baru</button><div className="cards">{savings.map(s=><article className="card pad" key={s.id}><div className="card-head"><div><h3>{s.name}</h3><p className="muted">{s.location}</p></div><button className="icon" onClick={()=>del('savings',s.id,'tabungan')}>Hapus</button></div><h2>{rp(sav(s.id))}</h2><button className="btn" onClick={()=>deposit(s)}>+ Deposit</button></article>)}</div></>}
 {active==='Hutang'&&<section className="card pad"><div className="card-head"><h2>Hutang & Cicilan</h2><button className="btn" onClick={addDebt}>+ Hutang</button></div><table><tbody>{debts.map(d=><tr key={d.id}><td><b>{d.name}</b><div className="muted">{d.source}</div></td><td>{rp(d.original_amount)}</td><td>{rp(debtLeft(d))}</td><td><button className="btn alt" onClick={()=>payDebt(d)}>+ Bayar</button></td><td><button className="icon" onClick={()=>del('debts',d.id,'hutang')}>Hapus</button></td></tr>)}</tbody></table></section>}
 {active==='Wishlist'&&<><button className="btn" onClick={addWish}>+ Wishlist</button><div className="cards">{wishes.map(w=>{const wp=parts.filter(p=>p.wishlist_id===w.id);return <article className="card pad" key={w.id}><div className="card-head"><div><div className="kicker">{w.brand}</div><h3>{w.name}</h3></div><button className="icon" onClick={()=>del('wishlists',w.id,'wishlist')}>Hapus</button></div><h2>{rp(w.saved)} / {rp(w.target)}</h2><div className="goalActions"><button className="btn" onClick={()=>saveWish(w)}>+ Tabung</button><button className="btn alt" onClick={()=>addPart(w)}>+ Tambah Part</button></div>{wp.map(p=><div className="partRow" key={p.id}><label><input type="checkbox" checked={!!p.bought} onChange={()=>togglePart(p)}/> {p.name} <span className="muted">{p.brand}</span></label><b>{rp(p.price)}</b><button className="icon" onClick={()=>del('wishlist_parts',p.id,'part')}>Hapus</button></div>)}</article>})}</div></>}
 </section></main>
}
