'use client';
import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {supabase} from '@/lib/supabase';
import QuickAddModal,{QuickAddKind} from './QuickAddModal';
import {Toast} from '@/app/components/UiKit';
type R=Record<string,any>;
const rp=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const sum=(a:R[],field='amount')=>a.reduce((s,x)=>s+Number(x[field]||0),0);
const z=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function safeDate(y:number,m:number,day:number){const last=new Date(y,m+1,0).getDate();return new Date(y,m,Math.min(day,last))}
function keyFor(date:string,startDay:number){const d=new Date(date+'T00:00:00');let y=d.getFullYear(),m=d.getMonth();const start=safeDate(y,m,startDay);if(d<start){m--;if(m<0){m=11;y--}}return `${y}-${String(m+1).padStart(2,'0')}`}
function bounds(key:string,startDay:number){const[y,m1]=key.split('-').map(Number),m=m1-1;const start=safeDate(y,m,startDay),end=safeDate(m===11?y+1:y,(m+1)%12,startDay),last=new Date(end);last.setDate(last.getDate()-1);return{start:z(start),end:z(end),last:z(last)}}
function labelRange(b:{start:string;last:string}){const f=new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric'});return `${f.format(new Date(b.start+'T00:00:00'))} – ${f.format(new Date(b.last+'T00:00:00'))}`}

export default function PeriodExperience({houses}:{houses:R[]}){
 const[uid,setUid]=useState(''),[hid,setHid]=useState(houses[0]?.id||''),[period,setPeriod]=useState(''),[financeOpen,setFinanceOpen]=useState(false),[tab,setTab]=useState('Income'),[quick,setQuick]=useState<QuickAddKind|null>(null),[toast,setToast]=useState('');
 const[income,setIncome]=useState<R[]>([]),[expenses,setExpenses]=useState<R[]>([]),[budgets,setBudgets]=useState<R[]>([]),[obligations,setObligations]=useState<R[]>([]),[debts,setDebts]=useState<R[]>([]),[debtPay,setDebtPay]=useState<R[]>([]),[savings,setSavings]=useState<R[]>([]),[savingTx,setSavingTx]=useState<R[]>([]),[etfs,setEtfs]=useState<R[]>([]),[etfTx,setEtfTx]=useState<R[]>([]),[golds,setGolds]=useState<R[]>([]),[goldTx,setGoldTx]=useState<R[]>([]),[stocks,setStocks]=useState<R[]>([]),[stockTx,setStockTx]=useState<R[]>([]);
 const[summaryPortal,setSummaryPortal]=useState<HTMLElement|null>(null),[controlPortal,setControlPortal]=useState<HTMLElement|null>(null),[dashboardActive,setDashboardActive]=useState(true);
 const house=houses.find(h=>h.id===hid)||houses[0],startDay=Number(house?.period_start_day||22),b=bounds(period||keyFor(today(),startDay),startDay),inside=(d:string)=>!!d&&d>=b.start&&d<b.end;
 async function child(table:string,col:string,ids:string[]){if(!ids.length)return[];const r=await supabase.from(table).select('*').in(col,ids);return r.data||[]}
 async function load(id:string){if(!id)return;const q=(t:string)=>supabase.from(t).select('*').eq('household_id',id).is('archived_at',null);const[a,c,d,e,f,g,h,i]=await Promise.all([q('income'),q('expenses'),q('budgets'),q('obligations'),q('debts'),q('savings'),q('etf_assets'),q('gold_assets')]);const s=await q('dividend_stocks');const db=f.data||[],sv=g.data||[],ea=h.data||[],ga=i.data||[],sa=s.data||[];setIncome(a.data||[]);setExpenses(c.data||[]);setBudgets(d.data||[]);setObligations(e.data||[]);setDebts(db);setSavings(sv);setEtfs(ea);setGolds(ga);setStocks(sa);const[dp,st,et,gt,sxt]=await Promise.all([child('debt_payments','debt_id',db.map(x=>x.id)),child('saving_transactions','saving_id',sv.map(x=>x.id)),child('etf_transactions','asset_id',ea.map(x=>x.id)),child('gold_transactions','asset_id',ga.map(x=>x.id)),child('dividend_stock_transactions','stock_id',sa.map(x=>x.id))]);setDebtPay(dp);setSavingTx(st);setEtfTx(et);setGoldTx(gt);setStockTx(sxt)}
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUid(data.user?.id||''));const first=houses[0];if(first){setHid(first.id);setPeriod(keyFor(today(),Number(first.period_start_day||22)));load(first.id)}},[houses]);
 useEffect(()=>{document.body.classList.add('period-aware-enabled');const onClick=(e:MouseEvent)=>{const btn=(e.target as HTMLElement)?.closest('button');if(!btn)return;const text=(btn.textContent||'').trim();if(text==='Finance'&&btn.closest('.refined-sidebar')){e.preventDefault();e.stopPropagation();setFinanceOpen(true);return}setTimeout(()=>{const active=document.querySelector('.refined-sidebar .nav-active');setDashboardActive((active?.textContent||'').trim()==='Dashboard')},0)};const onChange=(e:Event)=>{const el=e.target as HTMLSelectElement;if(el?.closest('.fv-actions')&&el.tagName==='SELECT'&&el.value){const hh=houses.find(h=>h.id===el.value);setHid(el.value);setPeriod(keyFor(today(),Number(hh?.period_start_day||22)));load(el.value)}};document.addEventListener('click',onClick,true);document.addEventListener('change',onChange,true);return()=>{document.body.classList.remove('period-aware-enabled');document.removeEventListener('click',onClick,true);document.removeEventListener('change',onChange,true)}},[houses]);
 useEffect(()=>{const head=document.querySelector('.refined-top'),actions=document.querySelector('.refined-top .fv-actions');if(!head||!actions)return;let a=document.getElementById('period-summary-portal');if(!a){a=document.createElement('div');a.id='period-summary-portal';head.insertAdjacentElement('afterend',a)}let c=document.getElementById('period-control-portal');if(!c){c=document.createElement('div');c.id='period-control-portal';actions.insertBefore(c,actions.firstChild)}setSummaryPortal(a);setControlPortal(c);return()=>{a?.remove();c?.remove()}},[dashboardActive]);
 const pi=income.filter(x=>inside(x.happened_at)),pe=expenses.filter(x=>inside(x.happened_at)),pob=obligations.filter(x=>inside(x.due_date)),pbud=budgets.filter(x=>x.period_start===b.start);
 const debtLeft=debts.reduce((s,d)=>s+Math.max(0,Number(d.original_amount||0)-sum(debtPay.filter(x=>x.debt_id===d.id))),0),totalSav=savings.reduce((s,x)=>s+sum(savingTx.filter(t=>t.saving_id===x.id)),0);
 const etfValue=etfs.reduce((s,a)=>{const t=etfTx.filter(x=>x.asset_id===a.id),net=Math.max(0,sum(t.filter(x=>x.type==='buy'))-sum(t.filter(x=>x.type==='sell')));return s+(Number(a.current_value||0)||net)},0);
 const goldValue=golds.reduce((s,a)=>{const t=goldTx.filter(x=>x.asset_id===a.id),grams=Math.max(0,t.filter(x=>x.type==='buy').reduce((n,x)=>n+Number(x.grams||0),0)-t.filter(x=>x.type==='sell').reduce((n,x)=>n+Number(x.grams||0),0));return s+grams*Number(a.current_price_per_gram||0)},0);
 const stockValue=stocks.reduce((s,a)=>{const t=stockTx.filter(x=>x.stock_id===a.id),units=Math.max(0,t.filter(x=>x.type==='buy').reduce((n,x)=>n+Number(x.units||0),0)-t.filter(x=>x.type==='sell').reduce((n,x)=>n+Number(x.units||0),0));return s+units*Number(a.current_price||0)},0);
 const ti=sum(pi),te=sum(pe),left=ti-te,netWorth=totalSav+etfValue+goldValue+stockValue-debtLeft,savingsRate=ti?Math.max(0,left/ti*100):0;
 async function refresh(msg?:string){await load(hid);if(msg)setToast(msg)}
 async function archive(table:string,id:string,label:string){if(!confirm(`Arsipkan ${label}?`))return;const r=await supabase.from(table).update({archived_at:new Date().toISOString()}).eq('id',id);if(r.error)setToast(r.error.message);else refresh(`${label} dipindahkan ke Arsip.`)}
 const control=controlPortal&&createPortal(<div className="period-aware-control"><span>Periode Household</span><input type="month" value={period||keyFor(today(),startDay)} onChange={e=>setPeriod(e.target.value)}/><small>{labelRange(b)}</small></div>,controlPortal);
 const summary=summaryPortal&&dashboardActive&&createPortal(<section className="grid5 period-aware-summary"><div className="card stat"><span>Income</span><strong>{rp(ti)}</strong><small>{labelRange(b)}</small></div><div className="card stat"><span>Expenses</span><strong>{rp(te)}</strong><small>{pe.length} transaksi</small></div><div className="card stat"><span>Sisa Cashflow</span><strong className={left>=0?'positive':'negative'}>{rp(left)}</strong><small>{savingsRate.toFixed(1)}% savings rate</small></div><div className="card stat"><span>Net Worth</span><strong>{rp(netWorth)}</strong><small>aset - hutang</small></div><div className="card stat"><span>Sisa Hutang</span><strong>{rp(debtLeft)}</strong><small>{debts.length} akun</small></div></section>,summaryPortal);
 return <>{control}{summary}{financeOpen&&<div className="finance-overlay"><div className="finance-overlay-panel"><header className="investment-overlay-head"><div><div className="kicker">Household Finance</div><h1>Keuangan · {house?.name}</h1><p className="muted">Periode {labelRange(b)} · dimulai setiap tanggal {startDay}</p></div><div className="action-row"><input type="month" value={period||keyFor(today(),startDay)} onChange={e=>setPeriod(e.target.value)}/><button className="btn alt" onClick={()=>setFinanceOpen(false)}>Tutup</button></div></header><div className="tabs">{['Income','Expenses','Budgeting','Kewajiban'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div>{tab==='Income'&&<FinanceTable title="Income" rows={pi} cols={[['happened_at','Tanggal'],['source','Sumber'],['amount','Nominal']]} onAdd={()=>setQuick('income')} onArchive={x=>archive('income',x.id,x.source)}/>} {tab==='Expenses'&&<FinanceTable title="Expenses" rows={pe} cols={[['happened_at','Tanggal'],['name','Keperluan'],['category','Kategori'],['amount','Nominal']]} onAdd={()=>setQuick('expense')} onArchive={x=>archive('expenses',x.id,x.name)}/>} {tab==='Budgeting'&&<section><div className="panel-line"><h2>Budgeting</h2><button className="btn" onClick={()=>setQuick('budget')}>＋ Budget</button></div><div className="budget-grid">{pbud.length===0?<p className="empty">Belum ada budget pada periode ini.</p>:pbud.map(x=>{const used=x.manual_used??sum(pe.filter(e=>(e.category||'').toLowerCase()===(x.category||'').toLowerCase()));const p=Number(x.amount)?Math.min(100,Number(used)/Number(x.amount)*100):0;return <article className="card pad" key={x.id}><div className="card-head"><b>{x.category}</b><button className="icon" onClick={()=>archive('budgets',x.id,x.category)}>Arsip</button></div><p>{rp(used)} / {rp(x.amount)}</p><div className="progress"><div style={{width:`${p}%`}}/></div></article>})}</div></section>} {tab==='Kewajiban'&&<FinanceTable title="Kewajiban" rows={pob} cols={[['due_date','Jatuh tempo'],['name','Nama'],['amount','Nominal'],['status','Status']]} onAdd={()=>setQuick('obligation')} onArchive={x=>archive('obligations',x.id,x.name)}/>}</div></div>}{quick&&<QuickAddModal kind={quick} open={!!quick} onClose={()=>setQuick(null)} hid={hid} uid={uid} period={{start:b.start,last:b.last}} assets={{etfs:[],golds:[],stocks:[],savings:[],debts:[],wishes:[]}} onSaved={refresh}/>}<Toast message={toast} tone="success" onDone={()=>setToast('')}/></>
}
function FinanceTable({title,rows,cols,onAdd,onArchive}:{title:string;rows:R[];cols:[string,string][];onAdd:()=>void;onArchive:(x:R)=>void}){return <section className="card pad"><div className="panel-line"><h2>{title}</h2><button className="btn" onClick={onAdd}>＋ {title}</button></div><div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}<th>Aksi</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={cols.length+1} className="empty">Belum ada data pada periode ini.</td></tr>:rows.map(x=><tr key={x.id}>{cols.map(c=><td key={c[0]}>{c[0]==='amount'?rp(x[c[0]]):String(x[c[0]]??'—')}</td>)}<td><button className="icon" onClick={()=>onArchive(x)}>Arsip</button></td></tr>)}</tbody></table></div></section>}
