'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {Modal} from '@/app/components/UiKit';

type R=Record<string,any>;
type Kind='income'|'expense'|'budget'|'obligation'|'savingGoal'|'savingDeposit'|'debt'|'debtPayment'|'etf'|'etfTx'|'gold'|'goldTx'|'stock'|'stockTx'|'dividend'|'wishlist'|'part'|'recurring';
type Field={key:string;label:string;type?:'text'|'number'|'date'|'url'|'select'|'textarea';placeholder?:string;options?:{value:string;label:string}[];required?:boolean;step?:string;defaultValue?:string};
const today=()=>new Date().toISOString().slice(0,10);
const titles:Record<Kind,string>={income:'Tambah Income',expense:'Tambah Expense',budget:'Tambah Budget',obligation:'Tambah Kewajiban',savingGoal:'Tambah Target Tabungan',savingDeposit:'Deposit Tabungan',debt:'Tambah Hutang',debtPayment:'Bayar Hutang',etf:'Tambah ETF',etfTx:'Transaksi ETF',gold:'Tambah Emas',goldTx:'Transaksi Emas',stock:'Tambah Saham Dividen',stockTx:'Transaksi Saham',dividend:'Catat Dividen',wishlist:'Tambah Wishlist',part:'Tambah Part Wishlist',recurring:'Transaksi Berulang'};

export default function QuickAddModal({kind,open,onClose,hid,uid,period,assets,onSaved}:{kind:Kind;open:boolean;onClose:()=>void;hid:string;uid:string;period:{start:string;last:string};assets:{etfs:R[];golds:R[];stocks:R[];savings:R[];debts:R[];wishes:R[]};onSaved:(message:string)=>Promise<void>|void}){
 const [form,setForm]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 const fields=useMemo<Field[]>(()=>{
  const opts=(rows:R[],label=(x:R)=>x.name||x.ticker)=>rows.map(x=>({value:x.id,label:label(x)}));
  switch(kind){
   case'income':return[{key:'source',label:'Sumber income',required:true},{key:'amount',label:'Nominal',type:'number',required:true},{key:'date',label:'Tanggal',type:'date',defaultValue:today(),required:true},{key:'note',label:'Catatan',type:'textarea'},{key:'tags',label:'Tags',placeholder:'gaji, sekolah'}];
   case'expense':return[{key:'name',label:'Keperluan',required:true},{key:'category',label:'Kategori',defaultValue:'Lainnya',required:true},{key:'amount',label:'Nominal',type:'number',required:true},{key:'date',label:'Tanggal',type:'date',defaultValue:today(),required:true},{key:'note',label:'Catatan',type:'textarea'},{key:'tags',label:'Tags',placeholder:'rumah, bayi'},{key:'receipt_url',label:'Link struk / bukti',type:'url'}];
   case'budget':return[{key:'category',label:'Kategori budget',required:true},{key:'amount',label:'Batas budget',type:'number',required:true},{key:'used',label:'Sudah terpakai',type:'number',defaultValue:'0'}];
   case'obligation':return[{key:'name',label:'Nama kewajiban',required:true},{key:'amount',label:'Nominal',type:'number',required:true},{key:'due_date',label:'Jatuh tempo',type:'date',defaultValue:period.start,required:true},{key:'reminder_days',label:'Ingatkan H- (hari)',type:'number',defaultValue:'3'},{key:'note',label:'Catatan',type:'textarea'}];
   case'savingGoal':return[{key:'name',label:'Nama target',required:true},{key:'location',label:'Lokasi / rekening',defaultValue:'Jago'},{key:'target',label:'Target',type:'number',required:true}];
   case'savingDeposit':return[{key:'saving_id',label:'Tabungan',type:'select',options:opts(assets.savings),required:true},{key:'amount',label:'Nominal deposit',type:'number',required:true},{key:'date',label:'Tanggal',type:'date',defaultValue:today(),required:true}];
   case'debt':return[{key:'name',label:'Nama hutang',required:true},{key:'source',label:'Sumber / kreditur'},{key:'amount',label:'Nilai awal',type:'number',required:true},{key:'date',label:'Tanggal mulai',type:'date',defaultValue:today(),required:true}];
   case'debtPayment':return[{key:'debt_id',label:'Hutang',type:'select',options:opts(assets.debts),required:true},{key:'amount',label:'Nominal pembayaran',type:'number',required:true},{key:'date',label:'Tanggal',type:'date',defaultValue:today(),required:true}];
   case'etf':return[{key:'ticker',label:'Ticker',required:true},{key:'name',label:'Nama ETF',required:true},{key:'broker',label:'Broker',defaultValue:'XTB'},{key:'current_price',label:'Harga sekarang',type:'number',defaultValue:'0'},{key:'current_value',label:'Nilai portofolio sekarang',type:'number',defaultValue:'0'},{key:'target_allocation',label:'Target alokasi (%)',type:'number',defaultValue:'0'}];
   case'etfTx':return[{key:'asset_id',label:'ETF',type:'select',options:opts(assets.etfs,x=>`${x.ticker} · ${x.name}`),required:true},{key:'type',label:'Jenis',type:'select',options:[{value:'buy',label:'Beli / Top up'},{value:'sell',label:'Jual'}],required:true},{key:'amount',label:'Nominal',type:'number',required:true},{key:'date',label:'Tanggal',type:'date',defaultValue:today(),required:true}];
   case'gold':return[{key:'name',label:'Nama aset emas',defaultValue:'Emas Digital',required:true},{key:'platform',label:'Platform',defaultValue:'Pluang'},{key:'price',label:'Harga sekarang / gram',type:'number',defaultValue:'0'},{key:'target_allocation',label:'Target alokasi (%)',type:'number',defaultValue:'0'}];
   case'goldTx':return[{key:'asset_id',label:'Aset emas',type:'select',options:opts(assets.golds),required:true},{key:'type',label:'Jenis',type:'select',options:[{value:'buy',label:'Beli'},{value:'sell',label:'Jual'}],required:true},{key:'amount',label:'Nominal',type:'number',required:true},{key:'grams',label:'Jumlah gram',type:'number',step:'0.000001',required:true},{key:'price',label:'Harga / gram',type:'number',required:true},{key:'date',label:'Tanggal',type:'date',defaultValue:today(),required:true}];
   case'stock':return[{key:'ticker',label:'Ticker',required:true},{key:'name',label:'Nama saham',required:true},{key:'broker',label:'Broker',defaultValue:'Pluang'},{key:'price',label:'Harga sekarang / lembar',type:'number',defaultValue:'0'},{key:'target_allocation',label:'Target alokasi (%)',type:'number',defaultValue:'0'}];
   case'stockTx':return[{key:'stock_id',label:'Saham',type:'select',options:opts(assets.stocks,x=>`${x.ticker} · ${x.name}`),required:true},{key:'type',label:'Jenis',type:'select',options:[{value:'buy',label:'Beli'},{value:'sell',label:'Jual'}],required:true},{key:'amount',label:'Nominal',type:'number',required:true},{key:'units',label:'Jumlah lembar',type:'number',step:'0.000001',required:true},{key:'date',label:'Tanggal',type:'date',defaultValue:today(),required:true}];
   case'dividend':return[{key:'stock_id',label:'Saham',type:'select',options:opts(assets.stocks,x=>`${x.ticker} · ${x.name}`),required:true},{key:'amount',label:'Dividen diterima',type:'number',required:true},{key:'date',label:'Tanggal',type:'date',defaultValue:today(),required:true}];
   case'wishlist':return[{key:'name',label:'Nama wishlist',required:true},{key:'brand',label:'Brand / model'},{key:'target',label:'Target harga',type:'number',required:true},{key:'saved',label:'Tabungan awal',type:'number',defaultValue:'0'},{key:'link',label:'Link produk',type:'url'},{key:'image_url',label:'Link gambar',type:'url'}];
   case'part':return[{key:'wishlist_id',label:'Wishlist',type:'select',options:opts(assets.wishes),required:true},{key:'name',label:'Nama part',required:true},{key:'brand',label:'Brand / model'},{key:'price',label:'Harga',type:'number',required:true},{key:'link',label:'Link produk',type:'url'}];
   case'recurring':return[{key:'kind',label:'Jenis',type:'select',options:[{value:'income',label:'Income'},{value:'expense',label:'Expense'},{value:'obligation',label:'Kewajiban'},{value:'saving',label:'Tabungan'}],required:true},{key:'name',label:'Nama',required:true},{key:'category',label:'Kategori / catatan'},{key:'amount',label:'Nominal',type:'number',required:true},{key:'frequency',label:'Frekuensi',type:'select',options:[{value:'weekly',label:'Mingguan'},{value:'monthly',label:'Bulanan'},{value:'yearly',label:'Tahunan'}],required:true},{key:'next_run',label:'Jadwal berikutnya',type:'date',defaultValue:today(),required:true}];
  }
 },[kind,assets,period.start]);
 useEffect(()=>{if(!open)return;const next:Record<string,string>={};for(const f of fields){if(f.defaultValue!==undefined)next[f.key]=f.defaultValue;else if(f.type==='select'&&f.options?.[0])next[f.key]=f.options[0].value}setForm(next);setErr('')},[open,kind,fields]);
 const n=(k:string)=>Number(form[k]||0),tags=()=>String(form.tags||'').split(',').map(x=>x.trim()).filter(Boolean);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setErr('');let r:any;try{
  switch(kind){
   case'income':r=await supabase.from('income').insert({household_id:hid,source:form.source,amount:n('amount'),happened_at:form.date,note:form.note||null,tags:tags(),created_by:uid});break;
   case'expense':r=await supabase.from('expenses').insert({household_id:hid,name:form.name,category:form.category||'Lainnya',amount:n('amount'),happened_at:form.date,note:form.note||null,tags:tags(),receipt_url:form.receipt_url||null,created_by:uid});break;
   case'budget':r=await supabase.from('budgets').insert({household_id:hid,category:form.category,amount:n('amount'),manual_used:n('used'),period_start:period.start,period_end:period.last,created_by:uid});break;
   case'obligation':r=await supabase.from('obligations').insert({household_id:hid,name:form.name,amount:n('amount'),status:'belum',due_date:form.due_date,reminder_days:n('reminder_days'),note:form.note||null,created_by:uid});break;
   case'savingGoal':r=await supabase.from('savings').insert({household_id:hid,name:form.name,location:form.location||null,target:n('target'),created_by:uid});break;
   case'savingDeposit':r=await supabase.from('saving_transactions').insert({saving_id:form.saving_id,amount:n('amount'),happened_at:form.date,created_by:uid});break;
   case'debt':r=await supabase.from('debts').insert({household_id:hid,name:form.name,source:form.source||null,original_amount:n('amount'),borrow_date:form.date,created_by:uid});break;
   case'debtPayment':r=await supabase.from('debt_payments').insert({debt_id:form.debt_id,amount:n('amount'),happened_at:form.date,created_by:uid});break;
   case'etf':r=await supabase.from('etf_assets').insert({household_id:hid,ticker:form.ticker.toUpperCase(),name:form.name,broker:form.broker||null,current_price:n('current_price'),current_value:n('current_value'),target_allocation:n('target_allocation'),created_by:uid});break;
   case'etfTx':r=await supabase.from('etf_transactions').insert({asset_id:form.asset_id,type:form.type,amount:n('amount'),happened_at:form.date,created_by:uid});break;
   case'gold':r=await supabase.from('gold_assets').insert({household_id:hid,name:form.name,platform:form.platform||null,current_price_per_gram:n('price'),target_allocation:n('target_allocation'),created_by:uid});break;
   case'goldTx':r=await supabase.from('gold_transactions').insert({asset_id:form.asset_id,type:form.type,amount:n('amount'),grams:n('grams'),price_per_gram:n('price'),happened_at:form.date,created_by:uid});break;
   case'stock':r=await supabase.from('dividend_stocks').insert({household_id:hid,ticker:form.ticker.toUpperCase(),name:form.name,broker:form.broker||null,current_price:n('price'),target_allocation:n('target_allocation'),created_by:uid});break;
   case'stockTx':r=await supabase.from('dividend_stock_transactions').insert({stock_id:form.stock_id,type:form.type,amount:n('amount'),units:n('units'),happened_at:form.date,created_by:uid});break;
   case'dividend':r=await supabase.from('dividends').insert({stock_id:form.stock_id,amount:n('amount'),happened_at:form.date,created_by:uid});break;
   case'wishlist':r=await supabase.from('wishlists').insert({household_id:hid,name:form.name,brand:form.brand||null,target:n('target'),saved:n('saved'),link:form.link||null,image_url:form.image_url||null,status:'active',created_by:uid});break;
   case'part':r=await supabase.from('wishlist_parts').insert({wishlist_id:form.wishlist_id,name:form.name,brand:form.brand||null,price:n('price'),link:form.link||null,bought:false,created_by:uid});break;
   case'recurring':r=await supabase.from('recurring_transactions').insert({household_id:hid,kind:form.kind,name:form.name,category:form.category||null,amount:n('amount'),frequency:form.frequency,next_run:form.next_run,active:true,created_by:uid});break;
  }
  if(r?.error)throw r.error;await onSaved(`${titles[kind]} berhasil disimpan.`);onClose();
 }catch(ex:any){setErr(ex.message||'Gagal menyimpan')}finally{setBusy(false)}}
 return <Modal open={open} title={titles[kind]} onClose={onClose} footer={<div className="fv-modal-actions"><button className="btn alt" onClick={onClose} type="button">Batal</button><button className="btn" form="quick-add-form" disabled={busy}>{busy?'Menyimpan…':'Simpan'}</button></div>}><form id="quick-add-form" onSubmit={submit} className="fv-form-grid">{fields.map(f=><label className={f.type==='textarea'?'span2':''} key={f.key}>{f.label}{f.type==='select'?<select value={form[f.key]||''} required={f.required} onChange={e=>setForm(v=>({...v,[f.key]:e.target.value}))}>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea value={form[f.key]||''} placeholder={f.placeholder} required={f.required} onChange={e=>setForm(v=>({...v,[f.key]:e.target.value}))}/>:<input type={f.type||'text'} step={f.step} value={form[f.key]||''} placeholder={f.placeholder} required={f.required} onChange={e=>setForm(v=>({...v,[f.key]:e.target.value}))}/>}</label>)}{err&&<div className="status error span2">{err}</div>}</form></Modal>
}

export type QuickAddKind=Kind;
